//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ActivityLogs = newActivityLogsTable("public", "activity_logs", "")

type activityLogsTable struct {
	postgres.Table

	// Columns
	ID         postgres.ColumnString
	CompanyID  postgres.ColumnString
	ActorID    postgres.ColumnString
	Action     postgres.ColumnString
	EntityType postgres.ColumnString
	EntityID   postgres.ColumnString
	Metadata   postgres.ColumnString
	CreatedAt  postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type ActivityLogsTable struct {
	activityLogsTable

	EXCLUDED activityLogsTable
}

// AS creates new ActivityLogsTable with assigned alias
func (a ActivityLogsTable) AS(alias string) *ActivityLogsTable {
	return newActivityLogsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ActivityLogsTable with assigned schema name
func (a ActivityLogsTable) FromSchema(schemaName string) *ActivityLogsTable {
	return newActivityLogsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ActivityLogsTable with assigned table prefix
func (a ActivityLogsTable) WithPrefix(prefix string) *ActivityLogsTable {
	return newActivityLogsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ActivityLogsTable with assigned table suffix
func (a ActivityLogsTable) WithSuffix(suffix string) *ActivityLogsTable {
	return newActivityLogsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newActivityLogsTable(schemaName, tableName, alias string) *ActivityLogsTable {
	return &ActivityLogsTable{
		activityLogsTable: newActivityLogsTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newActivityLogsTableImpl("", "excluded", ""),
	}
}

func newActivityLogsTableImpl(schemaName, tableName, alias string) activityLogsTable {
	var (
		IDColumn         = postgres.StringColumn("id")
		CompanyIDColumn  = postgres.StringColumn("company_id")
		ActorIDColumn    = postgres.StringColumn("actor_id")
		ActionColumn     = postgres.StringColumn("action")
		EntityTypeColumn = postgres.StringColumn("entity_type")
		EntityIDColumn   = postgres.StringColumn("entity_id")
		MetadataColumn   = postgres.StringColumn("metadata")
		CreatedAtColumn  = postgres.TimestampzColumn("created_at")
		allColumns       = postgres.ColumnList{IDColumn, CompanyIDColumn, ActorIDColumn, ActionColumn, EntityTypeColumn, EntityIDColumn, MetadataColumn, CreatedAtColumn}
		mutableColumns   = postgres.ColumnList{CompanyIDColumn, ActorIDColumn, ActionColumn, EntityTypeColumn, EntityIDColumn, MetadataColumn, CreatedAtColumn}
		defaultColumns   = postgres.ColumnList{IDColumn, MetadataColumn, CreatedAtColumn}
	)

	return activityLogsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:         IDColumn,
		CompanyID:  CompanyIDColumn,
		ActorID:    ActorIDColumn,
		Action:     ActionColumn,
		EntityType: EntityTypeColumn,
		EntityID:   EntityIDColumn,
		Metadata:   MetadataColumn,
		CreatedAt:  CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
