//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var AdminAuditLog = newAdminAuditLogTable("public", "admin_audit_log", "")

type adminAuditLogTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnString
	AdminID   postgres.ColumnString
	CompanyID postgres.ColumnString
	Action    postgres.ColumnString
	Reason    postgres.ColumnString
	CreatedAt postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type AdminAuditLogTable struct {
	adminAuditLogTable

	EXCLUDED adminAuditLogTable
}

// AS creates new AdminAuditLogTable with assigned alias
func (a AdminAuditLogTable) AS(alias string) *AdminAuditLogTable {
	return newAdminAuditLogTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AdminAuditLogTable with assigned schema name
func (a AdminAuditLogTable) FromSchema(schemaName string) *AdminAuditLogTable {
	return newAdminAuditLogTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AdminAuditLogTable with assigned table prefix
func (a AdminAuditLogTable) WithPrefix(prefix string) *AdminAuditLogTable {
	return newAdminAuditLogTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AdminAuditLogTable with assigned table suffix
func (a AdminAuditLogTable) WithSuffix(suffix string) *AdminAuditLogTable {
	return newAdminAuditLogTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAdminAuditLogTable(schemaName, tableName, alias string) *AdminAuditLogTable {
	return &AdminAuditLogTable{
		adminAuditLogTable: newAdminAuditLogTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newAdminAuditLogTableImpl("", "excluded", ""),
	}
}

func newAdminAuditLogTableImpl(schemaName, tableName, alias string) adminAuditLogTable {
	var (
		IDColumn        = postgres.StringColumn("id")
		AdminIDColumn   = postgres.StringColumn("admin_id")
		CompanyIDColumn = postgres.StringColumn("company_id")
		ActionColumn    = postgres.StringColumn("action")
		ReasonColumn    = postgres.StringColumn("reason")
		CreatedAtColumn = postgres.TimestampzColumn("created_at")
		allColumns      = postgres.ColumnList{IDColumn, AdminIDColumn, CompanyIDColumn, ActionColumn, ReasonColumn, CreatedAtColumn}
		mutableColumns  = postgres.ColumnList{AdminIDColumn, CompanyIDColumn, ActionColumn, ReasonColumn, CreatedAtColumn}
		defaultColumns  = postgres.ColumnList{IDColumn, CreatedAtColumn}
	)

	return adminAuditLogTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		AdminID:   AdminIDColumn,
		CompanyID: CompanyIDColumn,
		Action:    ActionColumn,
		Reason:    ReasonColumn,
		CreatedAt: CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
