//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var AiEvaluations = newAiEvaluationsTable("public", "ai_evaluations", "")

type aiEvaluationsTable struct {
	postgres.Table

	// Columns
	ID           postgres.ColumnString
	ProfileID    postgres.ColumnString
	OverallScore postgres.ColumnInteger
	Strengths    postgres.ColumnString
	Weaknesses   postgres.ColumnString
	Suggestions  postgres.ColumnString
	SkillScores  postgres.ColumnString
	RawAnalysis  postgres.ColumnString
	CreatedAt    postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type AiEvaluationsTable struct {
	aiEvaluationsTable

	EXCLUDED aiEvaluationsTable
}

// AS creates new AiEvaluationsTable with assigned alias
func (a AiEvaluationsTable) AS(alias string) *AiEvaluationsTable {
	return newAiEvaluationsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AiEvaluationsTable with assigned schema name
func (a AiEvaluationsTable) FromSchema(schemaName string) *AiEvaluationsTable {
	return newAiEvaluationsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AiEvaluationsTable with assigned table prefix
func (a AiEvaluationsTable) WithPrefix(prefix string) *AiEvaluationsTable {
	return newAiEvaluationsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AiEvaluationsTable with assigned table suffix
func (a AiEvaluationsTable) WithSuffix(suffix string) *AiEvaluationsTable {
	return newAiEvaluationsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAiEvaluationsTable(schemaName, tableName, alias string) *AiEvaluationsTable {
	return &AiEvaluationsTable{
		aiEvaluationsTable: newAiEvaluationsTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newAiEvaluationsTableImpl("", "excluded", ""),
	}
}

func newAiEvaluationsTableImpl(schemaName, tableName, alias string) aiEvaluationsTable {
	var (
		IDColumn           = postgres.StringColumn("id")
		ProfileIDColumn    = postgres.StringColumn("profile_id")
		OverallScoreColumn = postgres.IntegerColumn("overall_score")
		StrengthsColumn    = postgres.StringColumn("strengths")
		WeaknessesColumn   = postgres.StringColumn("weaknesses")
		SuggestionsColumn  = postgres.StringColumn("suggestions")
		SkillScoresColumn  = postgres.StringColumn("skill_scores")
		RawAnalysisColumn  = postgres.StringColumn("raw_analysis")
		CreatedAtColumn    = postgres.TimestampzColumn("created_at")
		allColumns         = postgres.ColumnList{IDColumn, ProfileIDColumn, OverallScoreColumn, StrengthsColumn, WeaknessesColumn, SuggestionsColumn, SkillScoresColumn, RawAnalysisColumn, CreatedAtColumn}
		mutableColumns     = postgres.ColumnList{ProfileIDColumn, OverallScoreColumn, StrengthsColumn, WeaknessesColumn, SuggestionsColumn, SkillScoresColumn, RawAnalysisColumn, CreatedAtColumn}
		defaultColumns     = postgres.ColumnList{IDColumn, StrengthsColumn, WeaknessesColumn, SuggestionsColumn, SkillScoresColumn, RawAnalysisColumn, CreatedAtColumn}
	)

	return aiEvaluationsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		ProfileID:    ProfileIDColumn,
		OverallScore: OverallScoreColumn,
		Strengths:    StrengthsColumn,
		Weaknesses:   WeaknessesColumn,
		Suggestions:  SuggestionsColumn,
		SkillScores:  SkillScoresColumn,
		RawAnalysis:  RawAnalysisColumn,
		CreatedAt:    CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
