//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ApplicationMessages = newApplicationMessagesTable("public", "application_messages", "")

type applicationMessagesTable struct {
	postgres.Table

	// Columns
	ID            postgres.ColumnString
	ApplicationID postgres.ColumnString
	SenderUserID  postgres.ColumnString
	MessageType   postgres.ColumnString
	Body          postgres.ColumnString
	CreatedAt     postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type ApplicationMessagesTable struct {
	applicationMessagesTable

	EXCLUDED applicationMessagesTable
}

// AS creates new ApplicationMessagesTable with assigned alias
func (a ApplicationMessagesTable) AS(alias string) *ApplicationMessagesTable {
	return newApplicationMessagesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ApplicationMessagesTable with assigned schema name
func (a ApplicationMessagesTable) FromSchema(schemaName string) *ApplicationMessagesTable {
	return newApplicationMessagesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ApplicationMessagesTable with assigned table prefix
func (a ApplicationMessagesTable) WithPrefix(prefix string) *ApplicationMessagesTable {
	return newApplicationMessagesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ApplicationMessagesTable with assigned table suffix
func (a ApplicationMessagesTable) WithSuffix(suffix string) *ApplicationMessagesTable {
	return newApplicationMessagesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newApplicationMessagesTable(schemaName, tableName, alias string) *ApplicationMessagesTable {
	return &ApplicationMessagesTable{
		applicationMessagesTable: newApplicationMessagesTableImpl(schemaName, tableName, alias),
		EXCLUDED:                 newApplicationMessagesTableImpl("", "excluded", ""),
	}
}

func newApplicationMessagesTableImpl(schemaName, tableName, alias string) applicationMessagesTable {
	var (
		IDColumn            = postgres.StringColumn("id")
		ApplicationIDColumn = postgres.StringColumn("application_id")
		SenderUserIDColumn  = postgres.StringColumn("sender_user_id")
		MessageTypeColumn   = postgres.StringColumn("message_type")
		BodyColumn          = postgres.StringColumn("body")
		CreatedAtColumn     = postgres.TimestampzColumn("created_at")
		allColumns          = postgres.ColumnList{IDColumn, ApplicationIDColumn, SenderUserIDColumn, MessageTypeColumn, BodyColumn, CreatedAtColumn}
		mutableColumns      = postgres.ColumnList{ApplicationIDColumn, SenderUserIDColumn, MessageTypeColumn, BodyColumn, CreatedAtColumn}
		defaultColumns      = postgres.ColumnList{IDColumn, MessageTypeColumn, CreatedAtColumn}
	)

	return applicationMessagesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:            IDColumn,
		ApplicationID: ApplicationIDColumn,
		SenderUserID:  SenderUserIDColumn,
		MessageType:   MessageTypeColumn,
		Body:          BodyColumn,
		CreatedAt:     CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
