//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Applications = newApplicationsTable("public", "applications", "")

type applicationsTable struct {
	postgres.Table

	// Columns
	ID           postgres.ColumnString
	JobseekerID  postgres.ColumnString
	JobPostingID postgres.ColumnString
	Status       postgres.ColumnString
	CreatedAt    postgres.ColumnTimestampz
	UpdatedAt    postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type ApplicationsTable struct {
	applicationsTable

	EXCLUDED applicationsTable
}

// AS creates new ApplicationsTable with assigned alias
func (a ApplicationsTable) AS(alias string) *ApplicationsTable {
	return newApplicationsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ApplicationsTable with assigned schema name
func (a ApplicationsTable) FromSchema(schemaName string) *ApplicationsTable {
	return newApplicationsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ApplicationsTable with assigned table prefix
func (a ApplicationsTable) WithPrefix(prefix string) *ApplicationsTable {
	return newApplicationsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ApplicationsTable with assigned table suffix
func (a ApplicationsTable) WithSuffix(suffix string) *ApplicationsTable {
	return newApplicationsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newApplicationsTable(schemaName, tableName, alias string) *ApplicationsTable {
	return &ApplicationsTable{
		applicationsTable: newApplicationsTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newApplicationsTableImpl("", "excluded", ""),
	}
}

func newApplicationsTableImpl(schemaName, tableName, alias string) applicationsTable {
	var (
		IDColumn           = postgres.StringColumn("id")
		JobseekerIDColumn  = postgres.StringColumn("jobseeker_id")
		JobPostingIDColumn = postgres.StringColumn("job_posting_id")
		StatusColumn       = postgres.StringColumn("status")
		CreatedAtColumn    = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn    = postgres.TimestampzColumn("updated_at")
		allColumns         = postgres.ColumnList{IDColumn, JobseekerIDColumn, JobPostingIDColumn, StatusColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns     = postgres.ColumnList{JobseekerIDColumn, JobPostingIDColumn, StatusColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns     = postgres.ColumnList{IDColumn, StatusColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return applicationsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		JobseekerID:  JobseekerIDColumn,
		JobPostingID: JobPostingIDColumn,
		Status:       StatusColumn,
		CreatedAt:    CreatedAtColumn,
		UpdatedAt:    UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
