//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var AttendanceLogs = newAttendanceLogsTable("public", "attendance_logs", "")

type attendanceLogsTable struct {
	postgres.Table

	// Columns
	ID              postgres.ColumnString
	CompanyID       postgres.ColumnString
	EmployeeID      postgres.ColumnString
	Date            postgres.ColumnDate
	ClockIn         postgres.ColumnTimestampz
	ClockOut        postgres.ColumnTimestampz
	ClockInLat      postgres.ColumnFloat
	ClockInLng      postgres.ColumnFloat
	ClockOutLat     postgres.ColumnFloat
	ClockOutLng     postgres.ColumnFloat
	BranchID        postgres.ColumnString
	IsInGeofence    postgres.ColumnBool
	IsLate          postgres.ColumnBool
	LateMinutes     postgres.ColumnInteger
	IsEarlyOut      postgres.ColumnBool
	OvertimeMinutes postgres.ColumnInteger
	AttendanceCode  postgres.ColumnString
	CreatedAt       postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type AttendanceLogsTable struct {
	attendanceLogsTable

	EXCLUDED attendanceLogsTable
}

// AS creates new AttendanceLogsTable with assigned alias
func (a AttendanceLogsTable) AS(alias string) *AttendanceLogsTable {
	return newAttendanceLogsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AttendanceLogsTable with assigned schema name
func (a AttendanceLogsTable) FromSchema(schemaName string) *AttendanceLogsTable {
	return newAttendanceLogsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AttendanceLogsTable with assigned table prefix
func (a AttendanceLogsTable) WithPrefix(prefix string) *AttendanceLogsTable {
	return newAttendanceLogsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AttendanceLogsTable with assigned table suffix
func (a AttendanceLogsTable) WithSuffix(suffix string) *AttendanceLogsTable {
	return newAttendanceLogsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAttendanceLogsTable(schemaName, tableName, alias string) *AttendanceLogsTable {
	return &AttendanceLogsTable{
		attendanceLogsTable: newAttendanceLogsTableImpl(schemaName, tableName, alias),
		EXCLUDED:            newAttendanceLogsTableImpl("", "excluded", ""),
	}
}

func newAttendanceLogsTableImpl(schemaName, tableName, alias string) attendanceLogsTable {
	var (
		IDColumn              = postgres.StringColumn("id")
		CompanyIDColumn       = postgres.StringColumn("company_id")
		EmployeeIDColumn      = postgres.StringColumn("employee_id")
		DateColumn            = postgres.DateColumn("date")
		ClockInColumn         = postgres.TimestampzColumn("clock_in")
		ClockOutColumn        = postgres.TimestampzColumn("clock_out")
		ClockInLatColumn      = postgres.FloatColumn("clock_in_lat")
		ClockInLngColumn      = postgres.FloatColumn("clock_in_lng")
		ClockOutLatColumn     = postgres.FloatColumn("clock_out_lat")
		ClockOutLngColumn     = postgres.FloatColumn("clock_out_lng")
		BranchIDColumn        = postgres.StringColumn("branch_id")
		IsInGeofenceColumn    = postgres.BoolColumn("is_in_geofence")
		IsLateColumn          = postgres.BoolColumn("is_late")
		LateMinutesColumn     = postgres.IntegerColumn("late_minutes")
		IsEarlyOutColumn      = postgres.BoolColumn("is_early_out")
		OvertimeMinutesColumn = postgres.IntegerColumn("overtime_minutes")
		AttendanceCodeColumn  = postgres.StringColumn("attendance_code")
		CreatedAtColumn       = postgres.TimestampzColumn("created_at")
		allColumns            = postgres.ColumnList{IDColumn, CompanyIDColumn, EmployeeIDColumn, DateColumn, ClockInColumn, ClockOutColumn, ClockInLatColumn, ClockInLngColumn, ClockOutLatColumn, ClockOutLngColumn, BranchIDColumn, IsInGeofenceColumn, IsLateColumn, LateMinutesColumn, IsEarlyOutColumn, OvertimeMinutesColumn, AttendanceCodeColumn, CreatedAtColumn}
		mutableColumns        = postgres.ColumnList{CompanyIDColumn, EmployeeIDColumn, DateColumn, ClockInColumn, ClockOutColumn, ClockInLatColumn, ClockInLngColumn, ClockOutLatColumn, ClockOutLngColumn, BranchIDColumn, IsInGeofenceColumn, IsLateColumn, LateMinutesColumn, IsEarlyOutColumn, OvertimeMinutesColumn, AttendanceCodeColumn, CreatedAtColumn}
		defaultColumns        = postgres.ColumnList{IDColumn, IsLateColumn, LateMinutesColumn, IsEarlyOutColumn, OvertimeMinutesColumn, AttendanceCodeColumn, CreatedAtColumn}
	)

	return attendanceLogsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:              IDColumn,
		CompanyID:       CompanyIDColumn,
		EmployeeID:      EmployeeIDColumn,
		Date:            DateColumn,
		ClockIn:         ClockInColumn,
		ClockOut:        ClockOutColumn,
		ClockInLat:      ClockInLatColumn,
		ClockInLng:      ClockInLngColumn,
		ClockOutLat:     ClockOutLatColumn,
		ClockOutLng:     ClockOutLngColumn,
		BranchID:        BranchIDColumn,
		IsInGeofence:    IsInGeofenceColumn,
		IsLate:          IsLateColumn,
		LateMinutes:     LateMinutesColumn,
		IsEarlyOut:      IsEarlyOutColumn,
		OvertimeMinutes: OvertimeMinutesColumn,
		AttendanceCode:  AttendanceCodeColumn,
		CreatedAt:       CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
