//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var AttendanceExceptions = newAttendanceExceptionsTable("public", "attendance_exceptions", "")

type attendanceExceptionsTable struct {
	postgres.Table

	// Columns
	ID              postgres.ColumnString
	CompanyID       postgres.ColumnString
	EmployeeID      postgres.ColumnString
	Date            postgres.ColumnDate
	ExceptionType   postgres.ColumnString
	Reason          postgres.ColumnString
	AttachmentURL   postgres.ColumnString
	Status          postgres.ColumnString
	ReviewerID      postgres.ColumnString
	ReviewerComment postgres.ColumnString
	ReviewedAt      postgres.ColumnTimestampz
	CreatedAt       postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type AttendanceExceptionsTable struct {
	attendanceExceptionsTable

	EXCLUDED attendanceExceptionsTable
}

// AS creates new AttendanceExceptionsTable with assigned alias
func (a AttendanceExceptionsTable) AS(alias string) *AttendanceExceptionsTable {
	return newAttendanceExceptionsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AttendanceExceptionsTable with assigned schema name
func (a AttendanceExceptionsTable) FromSchema(schemaName string) *AttendanceExceptionsTable {
	return newAttendanceExceptionsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AttendanceExceptionsTable with assigned table prefix
func (a AttendanceExceptionsTable) WithPrefix(prefix string) *AttendanceExceptionsTable {
	return newAttendanceExceptionsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AttendanceExceptionsTable with assigned table suffix
func (a AttendanceExceptionsTable) WithSuffix(suffix string) *AttendanceExceptionsTable {
	return newAttendanceExceptionsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAttendanceExceptionsTable(schemaName, tableName, alias string) *AttendanceExceptionsTable {
	return &AttendanceExceptionsTable{
		attendanceExceptionsTable: newAttendanceExceptionsTableImpl(schemaName, tableName, alias),
		EXCLUDED:                  newAttendanceExceptionsTableImpl("", "excluded", ""),
	}
}

func newAttendanceExceptionsTableImpl(schemaName, tableName, alias string) attendanceExceptionsTable {
	var (
		IDColumn              = postgres.StringColumn("id")
		CompanyIDColumn       = postgres.StringColumn("company_id")
		EmployeeIDColumn      = postgres.StringColumn("employee_id")
		DateColumn            = postgres.DateColumn("date")
		ExceptionTypeColumn   = postgres.StringColumn("exception_type")
		ReasonColumn          = postgres.StringColumn("reason")
		AttachmentURLColumn   = postgres.StringColumn("attachment_url")
		StatusColumn          = postgres.StringColumn("status")
		ReviewerIDColumn      = postgres.StringColumn("reviewer_id")
		ReviewerCommentColumn = postgres.StringColumn("reviewer_comment")
		ReviewedAtColumn      = postgres.TimestampzColumn("reviewed_at")
		CreatedAtColumn       = postgres.TimestampzColumn("created_at")
		allColumns            = postgres.ColumnList{IDColumn, CompanyIDColumn, EmployeeIDColumn, DateColumn, ExceptionTypeColumn, ReasonColumn, AttachmentURLColumn, StatusColumn, ReviewerIDColumn, ReviewerCommentColumn, ReviewedAtColumn, CreatedAtColumn}
		mutableColumns        = postgres.ColumnList{CompanyIDColumn, EmployeeIDColumn, DateColumn, ExceptionTypeColumn, ReasonColumn, AttachmentURLColumn, StatusColumn, ReviewerIDColumn, ReviewerCommentColumn, ReviewedAtColumn, CreatedAtColumn}
		defaultColumns        = postgres.ColumnList{IDColumn, StatusColumn, CreatedAtColumn}
	)

	return attendanceExceptionsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:              IDColumn,
		CompanyID:       CompanyIDColumn,
		EmployeeID:      EmployeeIDColumn,
		Date:            DateColumn,
		ExceptionType:   ExceptionTypeColumn,
		Reason:          ReasonColumn,
		AttachmentURL:   AttachmentURLColumn,
		Status:          StatusColumn,
		ReviewerID:      ReviewerIDColumn,
		ReviewerComment: ReviewerCommentColumn,
		ReviewedAt:      ReviewedAtColumn,
		CreatedAt:       CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
