//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Branches = newBranchesTable("public", "branches", "")

type branchesTable struct {
	postgres.Table

	// Columns
	ID                   postgres.ColumnString
	CompanyID            postgres.ColumnString
	Name                 postgres.ColumnString
	BranchType           postgres.ColumnString
	ParentBranchID       postgres.ColumnString
	Address              postgres.ColumnString
	City                 postgres.ColumnString
	Province             postgres.ColumnString
	Latitude             postgres.ColumnFloat
	Longitude            postgres.ColumnFloat
	GeofenceRadiusMeters postgres.ColumnInteger
	IsActive             postgres.ColumnBool
	CreatedAt            postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type BranchesTable struct {
	branchesTable

	EXCLUDED branchesTable
}

// AS creates new BranchesTable with assigned alias
func (a BranchesTable) AS(alias string) *BranchesTable {
	return newBranchesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new BranchesTable with assigned schema name
func (a BranchesTable) FromSchema(schemaName string) *BranchesTable {
	return newBranchesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new BranchesTable with assigned table prefix
func (a BranchesTable) WithPrefix(prefix string) *BranchesTable {
	return newBranchesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new BranchesTable with assigned table suffix
func (a BranchesTable) WithSuffix(suffix string) *BranchesTable {
	return newBranchesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newBranchesTable(schemaName, tableName, alias string) *BranchesTable {
	return &BranchesTable{
		branchesTable: newBranchesTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newBranchesTableImpl("", "excluded", ""),
	}
}

func newBranchesTableImpl(schemaName, tableName, alias string) branchesTable {
	var (
		IDColumn                   = postgres.StringColumn("id")
		CompanyIDColumn            = postgres.StringColumn("company_id")
		NameColumn                 = postgres.StringColumn("name")
		BranchTypeColumn           = postgres.StringColumn("branch_type")
		ParentBranchIDColumn       = postgres.StringColumn("parent_branch_id")
		AddressColumn              = postgres.StringColumn("address")
		CityColumn                 = postgres.StringColumn("city")
		ProvinceColumn             = postgres.StringColumn("province")
		LatitudeColumn             = postgres.FloatColumn("latitude")
		LongitudeColumn            = postgres.FloatColumn("longitude")
		GeofenceRadiusMetersColumn = postgres.IntegerColumn("geofence_radius_meters")
		IsActiveColumn             = postgres.BoolColumn("is_active")
		CreatedAtColumn            = postgres.TimestampzColumn("created_at")
		allColumns                 = postgres.ColumnList{IDColumn, CompanyIDColumn, NameColumn, BranchTypeColumn, ParentBranchIDColumn, AddressColumn, CityColumn, ProvinceColumn, LatitudeColumn, LongitudeColumn, GeofenceRadiusMetersColumn, IsActiveColumn, CreatedAtColumn}
		mutableColumns             = postgres.ColumnList{CompanyIDColumn, NameColumn, BranchTypeColumn, ParentBranchIDColumn, AddressColumn, CityColumn, ProvinceColumn, LatitudeColumn, LongitudeColumn, GeofenceRadiusMetersColumn, IsActiveColumn, CreatedAtColumn}
		defaultColumns             = postgres.ColumnList{IDColumn, BranchTypeColumn, GeofenceRadiusMetersColumn, IsActiveColumn, CreatedAtColumn}
	)

	return branchesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                   IDColumn,
		CompanyID:            CompanyIDColumn,
		Name:                 NameColumn,
		BranchType:           BranchTypeColumn,
		ParentBranchID:       ParentBranchIDColumn,
		Address:              AddressColumn,
		City:                 CityColumn,
		Province:             ProvinceColumn,
		Latitude:             LatitudeColumn,
		Longitude:            LongitudeColumn,
		GeofenceRadiusMeters: GeofenceRadiusMetersColumn,
		IsActive:             IsActiveColumn,
		CreatedAt:            CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
