//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var CareerPaths = newCareerPathsTable("public", "career_paths", "")

type careerPathsTable struct {
	postgres.Table

	// Columns
	ID                 postgres.ColumnString
	Title              postgres.ColumnString
	Description        postgres.ColumnString
	SkillRequirements  postgres.ColumnString
	TypicalProgression postgres.ColumnString
	Industry           postgres.ColumnString
	CreatedAt          postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type CareerPathsTable struct {
	careerPathsTable

	EXCLUDED careerPathsTable
}

// AS creates new CareerPathsTable with assigned alias
func (a CareerPathsTable) AS(alias string) *CareerPathsTable {
	return newCareerPathsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CareerPathsTable with assigned schema name
func (a CareerPathsTable) FromSchema(schemaName string) *CareerPathsTable {
	return newCareerPathsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CareerPathsTable with assigned table prefix
func (a CareerPathsTable) WithPrefix(prefix string) *CareerPathsTable {
	return newCareerPathsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CareerPathsTable with assigned table suffix
func (a CareerPathsTable) WithSuffix(suffix string) *CareerPathsTable {
	return newCareerPathsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCareerPathsTable(schemaName, tableName, alias string) *CareerPathsTable {
	return &CareerPathsTable{
		careerPathsTable: newCareerPathsTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newCareerPathsTableImpl("", "excluded", ""),
	}
}

func newCareerPathsTableImpl(schemaName, tableName, alias string) careerPathsTable {
	var (
		IDColumn                 = postgres.StringColumn("id")
		TitleColumn              = postgres.StringColumn("title")
		DescriptionColumn        = postgres.StringColumn("description")
		SkillRequirementsColumn  = postgres.StringColumn("skill_requirements")
		TypicalProgressionColumn = postgres.StringColumn("typical_progression")
		IndustryColumn           = postgres.StringColumn("industry")
		CreatedAtColumn          = postgres.TimestampzColumn("created_at")
		allColumns               = postgres.ColumnList{IDColumn, TitleColumn, DescriptionColumn, SkillRequirementsColumn, TypicalProgressionColumn, IndustryColumn, CreatedAtColumn}
		mutableColumns           = postgres.ColumnList{TitleColumn, DescriptionColumn, SkillRequirementsColumn, TypicalProgressionColumn, IndustryColumn, CreatedAtColumn}
		defaultColumns           = postgres.ColumnList{IDColumn, DescriptionColumn, SkillRequirementsColumn, TypicalProgressionColumn, IndustryColumn, CreatedAtColumn}
	)

	return careerPathsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                 IDColumn,
		Title:              TitleColumn,
		Description:        DescriptionColumn,
		SkillRequirements:  SkillRequirementsColumn,
		TypicalProgression: TypicalProgressionColumn,
		Industry:           IndustryColumn,
		CreatedAt:          CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
