//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Companies = newCompaniesTable("public", "companies", "")

type companiesTable struct {
	postgres.Table

	// Columns
	ID                 postgres.ColumnString
	UserID             postgres.ColumnString
	CompanyName        postgres.ColumnString
	Website            postgres.ColumnString
	Industry           postgres.ColumnString
	Description        postgres.ColumnString
	VerificationStatus postgres.ColumnString
	VerificationDocs   postgres.ColumnString
	VerifiedAt         postgres.ColumnTimestampz
	CreatedAt          postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type CompaniesTable struct {
	companiesTable

	EXCLUDED companiesTable
}

// AS creates new CompaniesTable with assigned alias
func (a CompaniesTable) AS(alias string) *CompaniesTable {
	return newCompaniesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CompaniesTable with assigned schema name
func (a CompaniesTable) FromSchema(schemaName string) *CompaniesTable {
	return newCompaniesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CompaniesTable with assigned table prefix
func (a CompaniesTable) WithPrefix(prefix string) *CompaniesTable {
	return newCompaniesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CompaniesTable with assigned table suffix
func (a CompaniesTable) WithSuffix(suffix string) *CompaniesTable {
	return newCompaniesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCompaniesTable(schemaName, tableName, alias string) *CompaniesTable {
	return &CompaniesTable{
		companiesTable: newCompaniesTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newCompaniesTableImpl("", "excluded", ""),
	}
}

func newCompaniesTableImpl(schemaName, tableName, alias string) companiesTable {
	var (
		IDColumn                 = postgres.StringColumn("id")
		UserIDColumn             = postgres.StringColumn("user_id")
		CompanyNameColumn        = postgres.StringColumn("company_name")
		WebsiteColumn            = postgres.StringColumn("website")
		IndustryColumn           = postgres.StringColumn("industry")
		DescriptionColumn        = postgres.StringColumn("description")
		VerificationStatusColumn = postgres.StringColumn("verification_status")
		VerificationDocsColumn   = postgres.StringColumn("verification_docs")
		VerifiedAtColumn         = postgres.TimestampzColumn("verified_at")
		CreatedAtColumn          = postgres.TimestampzColumn("created_at")
		allColumns               = postgres.ColumnList{IDColumn, UserIDColumn, CompanyNameColumn, WebsiteColumn, IndustryColumn, DescriptionColumn, VerificationStatusColumn, VerificationDocsColumn, VerifiedAtColumn, CreatedAtColumn}
		mutableColumns           = postgres.ColumnList{UserIDColumn, CompanyNameColumn, WebsiteColumn, IndustryColumn, DescriptionColumn, VerificationStatusColumn, VerificationDocsColumn, VerifiedAtColumn, CreatedAtColumn}
		defaultColumns           = postgres.ColumnList{IDColumn, VerificationStatusColumn, CreatedAtColumn}
	)

	return companiesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                 IDColumn,
		UserID:             UserIDColumn,
		CompanyName:        CompanyNameColumn,
		Website:            WebsiteColumn,
		Industry:           IndustryColumn,
		Description:        DescriptionColumn,
		VerificationStatus: VerificationStatusColumn,
		VerificationDocs:   VerificationDocsColumn,
		VerifiedAt:         VerifiedAtColumn,
		CreatedAt:          CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
