//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var CompanyWebhooks = newCompanyWebhooksTable("public", "company_webhooks", "")

type companyWebhooksTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnString
	CompanyID postgres.ColumnString
	URL       postgres.ColumnString
	Secret    postgres.ColumnString
	Active    postgres.ColumnBool
	CreatedAt postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type CompanyWebhooksTable struct {
	companyWebhooksTable

	EXCLUDED companyWebhooksTable
}

// AS creates new CompanyWebhooksTable with assigned alias
func (a CompanyWebhooksTable) AS(alias string) *CompanyWebhooksTable {
	return newCompanyWebhooksTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CompanyWebhooksTable with assigned schema name
func (a CompanyWebhooksTable) FromSchema(schemaName string) *CompanyWebhooksTable {
	return newCompanyWebhooksTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CompanyWebhooksTable with assigned table prefix
func (a CompanyWebhooksTable) WithPrefix(prefix string) *CompanyWebhooksTable {
	return newCompanyWebhooksTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CompanyWebhooksTable with assigned table suffix
func (a CompanyWebhooksTable) WithSuffix(suffix string) *CompanyWebhooksTable {
	return newCompanyWebhooksTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCompanyWebhooksTable(schemaName, tableName, alias string) *CompanyWebhooksTable {
	return &CompanyWebhooksTable{
		companyWebhooksTable: newCompanyWebhooksTableImpl(schemaName, tableName, alias),
		EXCLUDED:             newCompanyWebhooksTableImpl("", "excluded", ""),
	}
}

func newCompanyWebhooksTableImpl(schemaName, tableName, alias string) companyWebhooksTable {
	var (
		IDColumn        = postgres.StringColumn("id")
		CompanyIDColumn = postgres.StringColumn("company_id")
		URLColumn       = postgres.StringColumn("url")
		SecretColumn    = postgres.StringColumn("secret")
		ActiveColumn    = postgres.BoolColumn("active")
		CreatedAtColumn = postgres.TimestampzColumn("created_at")
		allColumns      = postgres.ColumnList{IDColumn, CompanyIDColumn, URLColumn, SecretColumn, ActiveColumn, CreatedAtColumn}
		mutableColumns  = postgres.ColumnList{CompanyIDColumn, URLColumn, SecretColumn, ActiveColumn, CreatedAtColumn}
		defaultColumns  = postgres.ColumnList{IDColumn, ActiveColumn, CreatedAtColumn}
	)

	return companyWebhooksTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		CompanyID: CompanyIDColumn,
		URL:       URLColumn,
		Secret:    SecretColumn,
		Active:    ActiveColumn,
		CreatedAt: CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
