//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var CompanyReviews = newCompanyReviewsTable("public", "company_reviews", "")

type companyReviewsTable struct {
	postgres.Table

	// Columns
	ID              postgres.ColumnString
	CompanyID       postgres.ColumnString
	CandidateID     postgres.ColumnString
	Rating          postgres.ColumnInteger
	Review          postgres.ColumnString
	InteractionType postgres.ColumnString
	CreatedAt       postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type CompanyReviewsTable struct {
	companyReviewsTable

	EXCLUDED companyReviewsTable
}

// AS creates new CompanyReviewsTable with assigned alias
func (a CompanyReviewsTable) AS(alias string) *CompanyReviewsTable {
	return newCompanyReviewsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CompanyReviewsTable with assigned schema name
func (a CompanyReviewsTable) FromSchema(schemaName string) *CompanyReviewsTable {
	return newCompanyReviewsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CompanyReviewsTable with assigned table prefix
func (a CompanyReviewsTable) WithPrefix(prefix string) *CompanyReviewsTable {
	return newCompanyReviewsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CompanyReviewsTable with assigned table suffix
func (a CompanyReviewsTable) WithSuffix(suffix string) *CompanyReviewsTable {
	return newCompanyReviewsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCompanyReviewsTable(schemaName, tableName, alias string) *CompanyReviewsTable {
	return &CompanyReviewsTable{
		companyReviewsTable: newCompanyReviewsTableImpl(schemaName, tableName, alias),
		EXCLUDED:            newCompanyReviewsTableImpl("", "excluded", ""),
	}
}

func newCompanyReviewsTableImpl(schemaName, tableName, alias string) companyReviewsTable {
	var (
		IDColumn              = postgres.StringColumn("id")
		CompanyIDColumn       = postgres.StringColumn("company_id")
		CandidateIDColumn     = postgres.StringColumn("candidate_id")
		RatingColumn          = postgres.IntegerColumn("rating")
		ReviewColumn          = postgres.StringColumn("review")
		InteractionTypeColumn = postgres.StringColumn("interaction_type")
		CreatedAtColumn       = postgres.TimestampzColumn("created_at")
		allColumns            = postgres.ColumnList{IDColumn, CompanyIDColumn, CandidateIDColumn, RatingColumn, ReviewColumn, InteractionTypeColumn, CreatedAtColumn}
		mutableColumns        = postgres.ColumnList{CompanyIDColumn, CandidateIDColumn, RatingColumn, ReviewColumn, InteractionTypeColumn, CreatedAtColumn}
		defaultColumns        = postgres.ColumnList{IDColumn, CreatedAtColumn}
	)

	return companyReviewsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:              IDColumn,
		CompanyID:       CompanyIDColumn,
		CandidateID:     CandidateIDColumn,
		Rating:          RatingColumn,
		Review:          ReviewColumn,
		InteractionType: InteractionTypeColumn,
		CreatedAt:       CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
