//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var EmployeeRoles = newEmployeeRolesTable("public", "employee_roles", "")

type employeeRolesTable struct {
	postgres.Table

	// Columns
	EmployeeID postgres.ColumnString
	RoleID     postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type EmployeeRolesTable struct {
	employeeRolesTable

	EXCLUDED employeeRolesTable
}

// AS creates new EmployeeRolesTable with assigned alias
func (a EmployeeRolesTable) AS(alias string) *EmployeeRolesTable {
	return newEmployeeRolesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new EmployeeRolesTable with assigned schema name
func (a EmployeeRolesTable) FromSchema(schemaName string) *EmployeeRolesTable {
	return newEmployeeRolesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new EmployeeRolesTable with assigned table prefix
func (a EmployeeRolesTable) WithPrefix(prefix string) *EmployeeRolesTable {
	return newEmployeeRolesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new EmployeeRolesTable with assigned table suffix
func (a EmployeeRolesTable) WithSuffix(suffix string) *EmployeeRolesTable {
	return newEmployeeRolesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newEmployeeRolesTable(schemaName, tableName, alias string) *EmployeeRolesTable {
	return &EmployeeRolesTable{
		employeeRolesTable: newEmployeeRolesTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newEmployeeRolesTableImpl("", "excluded", ""),
	}
}

func newEmployeeRolesTableImpl(schemaName, tableName, alias string) employeeRolesTable {
	var (
		EmployeeIDColumn = postgres.StringColumn("employee_id")
		RoleIDColumn     = postgres.StringColumn("role_id")
		allColumns       = postgres.ColumnList{EmployeeIDColumn, RoleIDColumn}
		mutableColumns   = postgres.ColumnList{}
		defaultColumns   = postgres.ColumnList{}
	)

	return employeeRolesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		EmployeeID: EmployeeIDColumn,
		RoleID:     RoleIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
