//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var EmployeeSalary = newEmployeeSalaryTable("public", "employee_salary", "")

type employeeSalaryTable struct {
	postgres.Table

	// Columns
	ID            postgres.ColumnString
	EmployeeID    postgres.ColumnString
	ComponentID   postgres.ColumnString
	Amount        postgres.ColumnFloat
	EffectiveDate postgres.ColumnDate
	CreatedAt     postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type EmployeeSalaryTable struct {
	employeeSalaryTable

	EXCLUDED employeeSalaryTable
}

// AS creates new EmployeeSalaryTable with assigned alias
func (a EmployeeSalaryTable) AS(alias string) *EmployeeSalaryTable {
	return newEmployeeSalaryTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new EmployeeSalaryTable with assigned schema name
func (a EmployeeSalaryTable) FromSchema(schemaName string) *EmployeeSalaryTable {
	return newEmployeeSalaryTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new EmployeeSalaryTable with assigned table prefix
func (a EmployeeSalaryTable) WithPrefix(prefix string) *EmployeeSalaryTable {
	return newEmployeeSalaryTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new EmployeeSalaryTable with assigned table suffix
func (a EmployeeSalaryTable) WithSuffix(suffix string) *EmployeeSalaryTable {
	return newEmployeeSalaryTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newEmployeeSalaryTable(schemaName, tableName, alias string) *EmployeeSalaryTable {
	return &EmployeeSalaryTable{
		employeeSalaryTable: newEmployeeSalaryTableImpl(schemaName, tableName, alias),
		EXCLUDED:            newEmployeeSalaryTableImpl("", "excluded", ""),
	}
}

func newEmployeeSalaryTableImpl(schemaName, tableName, alias string) employeeSalaryTable {
	var (
		IDColumn            = postgres.StringColumn("id")
		EmployeeIDColumn    = postgres.StringColumn("employee_id")
		ComponentIDColumn   = postgres.StringColumn("component_id")
		AmountColumn        = postgres.FloatColumn("amount")
		EffectiveDateColumn = postgres.DateColumn("effective_date")
		CreatedAtColumn     = postgres.TimestampzColumn("created_at")
		allColumns          = postgres.ColumnList{IDColumn, EmployeeIDColumn, ComponentIDColumn, AmountColumn, EffectiveDateColumn, CreatedAtColumn}
		mutableColumns      = postgres.ColumnList{EmployeeIDColumn, ComponentIDColumn, AmountColumn, EffectiveDateColumn, CreatedAtColumn}
		defaultColumns      = postgres.ColumnList{IDColumn, AmountColumn, EffectiveDateColumn, CreatedAtColumn}
	)

	return employeeSalaryTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:            IDColumn,
		EmployeeID:    EmployeeIDColumn,
		ComponentID:   ComponentIDColumn,
		Amount:        AmountColumn,
		EffectiveDate: EffectiveDateColumn,
		CreatedAt:     CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
