//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var EmployeeIDConfigs = newEmployeeIDConfigsTable("public", "employee_id_configs", "")

type employeeIDConfigsTable struct {
	postgres.Table

	// Columns
	ID           postgres.ColumnString
	CompanyID    postgres.ColumnString
	Prefix       postgres.ColumnString
	NextSequence postgres.ColumnInteger
	Padding      postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type EmployeeIDConfigsTable struct {
	employeeIDConfigsTable

	EXCLUDED employeeIDConfigsTable
}

// AS creates new EmployeeIDConfigsTable with assigned alias
func (a EmployeeIDConfigsTable) AS(alias string) *EmployeeIDConfigsTable {
	return newEmployeeIDConfigsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new EmployeeIDConfigsTable with assigned schema name
func (a EmployeeIDConfigsTable) FromSchema(schemaName string) *EmployeeIDConfigsTable {
	return newEmployeeIDConfigsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new EmployeeIDConfigsTable with assigned table prefix
func (a EmployeeIDConfigsTable) WithPrefix(prefix string) *EmployeeIDConfigsTable {
	return newEmployeeIDConfigsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new EmployeeIDConfigsTable with assigned table suffix
func (a EmployeeIDConfigsTable) WithSuffix(suffix string) *EmployeeIDConfigsTable {
	return newEmployeeIDConfigsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newEmployeeIDConfigsTable(schemaName, tableName, alias string) *EmployeeIDConfigsTable {
	return &EmployeeIDConfigsTable{
		employeeIDConfigsTable: newEmployeeIDConfigsTableImpl(schemaName, tableName, alias),
		EXCLUDED:               newEmployeeIDConfigsTableImpl("", "excluded", ""),
	}
}

func newEmployeeIDConfigsTableImpl(schemaName, tableName, alias string) employeeIDConfigsTable {
	var (
		IDColumn           = postgres.StringColumn("id")
		CompanyIDColumn    = postgres.StringColumn("company_id")
		PrefixColumn       = postgres.StringColumn("prefix")
		NextSequenceColumn = postgres.IntegerColumn("next_sequence")
		PaddingColumn      = postgres.IntegerColumn("padding")
		allColumns         = postgres.ColumnList{IDColumn, CompanyIDColumn, PrefixColumn, NextSequenceColumn, PaddingColumn}
		mutableColumns     = postgres.ColumnList{CompanyIDColumn, PrefixColumn, NextSequenceColumn, PaddingColumn}
		defaultColumns     = postgres.ColumnList{IDColumn, PrefixColumn, NextSequenceColumn, PaddingColumn}
	)

	return employeeIDConfigsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		CompanyID:    CompanyIDColumn,
		Prefix:       PrefixColumn,
		NextSequence: NextSequenceColumn,
		Padding:      PaddingColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
