//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Employees = newEmployeesTable("public", "employees", "")

type employeesTable struct {
	postgres.Table

	// Columns
	ID                       postgres.ColumnString
	CompanyID                postgres.ColumnString
	UserID                   postgres.ColumnString
	EmployeeIDNumber         postgres.ColumnString
	FirstName                postgres.ColumnString
	LastName                 postgres.ColumnString
	Email                    postgres.ColumnString
	Phone                    postgres.ColumnString
	DateOfBirth              postgres.ColumnDate
	Gender                   postgres.ColumnString
	MaritalStatus            postgres.ColumnString
	Address                  postgres.ColumnString
	City                     postgres.ColumnString
	Province                 postgres.ColumnString
	PostalCode               postgres.ColumnString
	NationalID               postgres.ColumnString
	Npwp                     postgres.ColumnString
	BpjsKesehatanID          postgres.ColumnString
	BpjsKetenagakerjaanID    postgres.ColumnString
	BankName                 postgres.ColumnString
	BankAccountNumber        postgres.ColumnString
	BankAccountHolder        postgres.ColumnString
	EmergencyContactName     postgres.ColumnString
	EmergencyContactPhone    postgres.ColumnString
	EmergencyContactRelation postgres.ColumnString
	EmploymentType           postgres.ColumnString
	EmploymentStatus         postgres.ColumnString
	JoinDate                 postgres.ColumnDate
	EndDate                  postgres.ColumnDate
	DepartmentID             postgres.ColumnString
	PositionID               postgres.ColumnString
	BranchID                 postgres.ColumnString
	ManagerID                postgres.ColumnString
	BaseSalary               postgres.ColumnFloat
	CreatedAt                postgres.ColumnTimestampz
	UpdatedAt                postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type EmployeesTable struct {
	employeesTable

	EXCLUDED employeesTable
}

// AS creates new EmployeesTable with assigned alias
func (a EmployeesTable) AS(alias string) *EmployeesTable {
	return newEmployeesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new EmployeesTable with assigned schema name
func (a EmployeesTable) FromSchema(schemaName string) *EmployeesTable {
	return newEmployeesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new EmployeesTable with assigned table prefix
func (a EmployeesTable) WithPrefix(prefix string) *EmployeesTable {
	return newEmployeesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new EmployeesTable with assigned table suffix
func (a EmployeesTable) WithSuffix(suffix string) *EmployeesTable {
	return newEmployeesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newEmployeesTable(schemaName, tableName, alias string) *EmployeesTable {
	return &EmployeesTable{
		employeesTable: newEmployeesTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newEmployeesTableImpl("", "excluded", ""),
	}
}

func newEmployeesTableImpl(schemaName, tableName, alias string) employeesTable {
	var (
		IDColumn                       = postgres.StringColumn("id")
		CompanyIDColumn                = postgres.StringColumn("company_id")
		UserIDColumn                   = postgres.StringColumn("user_id")
		EmployeeIDNumberColumn         = postgres.StringColumn("employee_id_number")
		FirstNameColumn                = postgres.StringColumn("first_name")
		LastNameColumn                 = postgres.StringColumn("last_name")
		EmailColumn                    = postgres.StringColumn("email")
		PhoneColumn                    = postgres.StringColumn("phone")
		DateOfBirthColumn              = postgres.DateColumn("date_of_birth")
		GenderColumn                   = postgres.StringColumn("gender")
		MaritalStatusColumn            = postgres.StringColumn("marital_status")
		AddressColumn                  = postgres.StringColumn("address")
		CityColumn                     = postgres.StringColumn("city")
		ProvinceColumn                 = postgres.StringColumn("province")
		PostalCodeColumn               = postgres.StringColumn("postal_code")
		NationalIDColumn               = postgres.StringColumn("national_id")
		NpwpColumn                     = postgres.StringColumn("npwp")
		BpjsKesehatanIDColumn          = postgres.StringColumn("bpjs_kesehatan_id")
		BpjsKetenagakerjaanIDColumn    = postgres.StringColumn("bpjs_ketenagakerjaan_id")
		BankNameColumn                 = postgres.StringColumn("bank_name")
		BankAccountNumberColumn        = postgres.StringColumn("bank_account_number")
		BankAccountHolderColumn        = postgres.StringColumn("bank_account_holder")
		EmergencyContactNameColumn     = postgres.StringColumn("emergency_contact_name")
		EmergencyContactPhoneColumn    = postgres.StringColumn("emergency_contact_phone")
		EmergencyContactRelationColumn = postgres.StringColumn("emergency_contact_relation")
		EmploymentTypeColumn           = postgres.StringColumn("employment_type")
		EmploymentStatusColumn         = postgres.StringColumn("employment_status")
		JoinDateColumn                 = postgres.DateColumn("join_date")
		EndDateColumn                  = postgres.DateColumn("end_date")
		DepartmentIDColumn             = postgres.StringColumn("department_id")
		PositionIDColumn               = postgres.StringColumn("position_id")
		BranchIDColumn                 = postgres.StringColumn("branch_id")
		ManagerIDColumn                = postgres.StringColumn("manager_id")
		BaseSalaryColumn               = postgres.FloatColumn("base_salary")
		CreatedAtColumn                = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn                = postgres.TimestampzColumn("updated_at")
		allColumns                     = postgres.ColumnList{IDColumn, CompanyIDColumn, UserIDColumn, EmployeeIDNumberColumn, FirstNameColumn, LastNameColumn, EmailColumn, PhoneColumn, DateOfBirthColumn, GenderColumn, MaritalStatusColumn, AddressColumn, CityColumn, ProvinceColumn, PostalCodeColumn, NationalIDColumn, NpwpColumn, BpjsKesehatanIDColumn, BpjsKetenagakerjaanIDColumn, BankNameColumn, BankAccountNumberColumn, BankAccountHolderColumn, EmergencyContactNameColumn, EmergencyContactPhoneColumn, EmergencyContactRelationColumn, EmploymentTypeColumn, EmploymentStatusColumn, JoinDateColumn, EndDateColumn, DepartmentIDColumn, PositionIDColumn, BranchIDColumn, ManagerIDColumn, BaseSalaryColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns                 = postgres.ColumnList{CompanyIDColumn, UserIDColumn, EmployeeIDNumberColumn, FirstNameColumn, LastNameColumn, EmailColumn, PhoneColumn, DateOfBirthColumn, GenderColumn, MaritalStatusColumn, AddressColumn, CityColumn, ProvinceColumn, PostalCodeColumn, NationalIDColumn, NpwpColumn, BpjsKesehatanIDColumn, BpjsKetenagakerjaanIDColumn, BankNameColumn, BankAccountNumberColumn, BankAccountHolderColumn, EmergencyContactNameColumn, EmergencyContactPhoneColumn, EmergencyContactRelationColumn, EmploymentTypeColumn, EmploymentStatusColumn, JoinDateColumn, EndDateColumn, DepartmentIDColumn, PositionIDColumn, BranchIDColumn, ManagerIDColumn, BaseSalaryColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns                 = postgres.ColumnList{IDColumn, LastNameColumn, EmploymentTypeColumn, EmploymentStatusColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return employeesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                       IDColumn,
		CompanyID:                CompanyIDColumn,
		UserID:                   UserIDColumn,
		EmployeeIDNumber:         EmployeeIDNumberColumn,
		FirstName:                FirstNameColumn,
		LastName:                 LastNameColumn,
		Email:                    EmailColumn,
		Phone:                    PhoneColumn,
		DateOfBirth:              DateOfBirthColumn,
		Gender:                   GenderColumn,
		MaritalStatus:            MaritalStatusColumn,
		Address:                  AddressColumn,
		City:                     CityColumn,
		Province:                 ProvinceColumn,
		PostalCode:               PostalCodeColumn,
		NationalID:               NationalIDColumn,
		Npwp:                     NpwpColumn,
		BpjsKesehatanID:          BpjsKesehatanIDColumn,
		BpjsKetenagakerjaanID:    BpjsKetenagakerjaanIDColumn,
		BankName:                 BankNameColumn,
		BankAccountNumber:        BankAccountNumberColumn,
		BankAccountHolder:        BankAccountHolderColumn,
		EmergencyContactName:     EmergencyContactNameColumn,
		EmergencyContactPhone:    EmergencyContactPhoneColumn,
		EmergencyContactRelation: EmergencyContactRelationColumn,
		EmploymentType:           EmploymentTypeColumn,
		EmploymentStatus:         EmploymentStatusColumn,
		JoinDate:                 JoinDateColumn,
		EndDate:                  EndDateColumn,
		DepartmentID:             DepartmentIDColumn,
		PositionID:               PositionIDColumn,
		BranchID:                 BranchIDColumn,
		ManagerID:                ManagerIDColumn,
		BaseSalary:               BaseSalaryColumn,
		CreatedAt:                CreatedAtColumn,
		UpdatedAt:                UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
