//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var EmployeeShifts = newEmployeeShiftsTable("public", "employee_shifts", "")

type employeeShiftsTable struct {
	postgres.Table

	// Columns
	ID            postgres.ColumnString
	EmployeeID    postgres.ColumnString
	ShiftID       postgres.ColumnString
	EffectiveDate postgres.ColumnDate
	EndDate       postgres.ColumnDate
	CreatedAt     postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type EmployeeShiftsTable struct {
	employeeShiftsTable

	EXCLUDED employeeShiftsTable
}

// AS creates new EmployeeShiftsTable with assigned alias
func (a EmployeeShiftsTable) AS(alias string) *EmployeeShiftsTable {
	return newEmployeeShiftsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new EmployeeShiftsTable with assigned schema name
func (a EmployeeShiftsTable) FromSchema(schemaName string) *EmployeeShiftsTable {
	return newEmployeeShiftsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new EmployeeShiftsTable with assigned table prefix
func (a EmployeeShiftsTable) WithPrefix(prefix string) *EmployeeShiftsTable {
	return newEmployeeShiftsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new EmployeeShiftsTable with assigned table suffix
func (a EmployeeShiftsTable) WithSuffix(suffix string) *EmployeeShiftsTable {
	return newEmployeeShiftsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newEmployeeShiftsTable(schemaName, tableName, alias string) *EmployeeShiftsTable {
	return &EmployeeShiftsTable{
		employeeShiftsTable: newEmployeeShiftsTableImpl(schemaName, tableName, alias),
		EXCLUDED:            newEmployeeShiftsTableImpl("", "excluded", ""),
	}
}

func newEmployeeShiftsTableImpl(schemaName, tableName, alias string) employeeShiftsTable {
	var (
		IDColumn            = postgres.StringColumn("id")
		EmployeeIDColumn    = postgres.StringColumn("employee_id")
		ShiftIDColumn       = postgres.StringColumn("shift_id")
		EffectiveDateColumn = postgres.DateColumn("effective_date")
		EndDateColumn       = postgres.DateColumn("end_date")
		CreatedAtColumn     = postgres.TimestampzColumn("created_at")
		allColumns          = postgres.ColumnList{IDColumn, EmployeeIDColumn, ShiftIDColumn, EffectiveDateColumn, EndDateColumn, CreatedAtColumn}
		mutableColumns      = postgres.ColumnList{EmployeeIDColumn, ShiftIDColumn, EffectiveDateColumn, EndDateColumn, CreatedAtColumn}
		defaultColumns      = postgres.ColumnList{IDColumn, CreatedAtColumn}
	)

	return employeeShiftsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:            IDColumn,
		EmployeeID:    EmployeeIDColumn,
		ShiftID:       ShiftIDColumn,
		EffectiveDate: EffectiveDateColumn,
		EndDate:       EndDateColumn,
		CreatedAt:     CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
