//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Feedback = newFeedbackTable("public", "feedback", "")

type feedbackTable struct {
	postgres.Table

	// Columns
	ID            postgres.ColumnString
	ProfileID     postgres.ColumnString
	CompanyID     postgres.ColumnString
	Content       postgres.ColumnString
	RatingAreas   postgres.ColumnString
	AiSuggestions postgres.ColumnString
	CreatedAt     postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type FeedbackTable struct {
	feedbackTable

	EXCLUDED feedbackTable
}

// AS creates new FeedbackTable with assigned alias
func (a FeedbackTable) AS(alias string) *FeedbackTable {
	return newFeedbackTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FeedbackTable with assigned schema name
func (a FeedbackTable) FromSchema(schemaName string) *FeedbackTable {
	return newFeedbackTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FeedbackTable with assigned table prefix
func (a FeedbackTable) WithPrefix(prefix string) *FeedbackTable {
	return newFeedbackTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FeedbackTable with assigned table suffix
func (a FeedbackTable) WithSuffix(suffix string) *FeedbackTable {
	return newFeedbackTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFeedbackTable(schemaName, tableName, alias string) *FeedbackTable {
	return &FeedbackTable{
		feedbackTable: newFeedbackTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newFeedbackTableImpl("", "excluded", ""),
	}
}

func newFeedbackTableImpl(schemaName, tableName, alias string) feedbackTable {
	var (
		IDColumn            = postgres.StringColumn("id")
		ProfileIDColumn     = postgres.StringColumn("profile_id")
		CompanyIDColumn     = postgres.StringColumn("company_id")
		ContentColumn       = postgres.StringColumn("content")
		RatingAreasColumn   = postgres.StringColumn("rating_areas")
		AiSuggestionsColumn = postgres.StringColumn("ai_suggestions")
		CreatedAtColumn     = postgres.TimestampzColumn("created_at")
		allColumns          = postgres.ColumnList{IDColumn, ProfileIDColumn, CompanyIDColumn, ContentColumn, RatingAreasColumn, AiSuggestionsColumn, CreatedAtColumn}
		mutableColumns      = postgres.ColumnList{ProfileIDColumn, CompanyIDColumn, ContentColumn, RatingAreasColumn, AiSuggestionsColumn, CreatedAtColumn}
		defaultColumns      = postgres.ColumnList{IDColumn, ContentColumn, RatingAreasColumn, AiSuggestionsColumn, CreatedAtColumn}
	)

	return feedbackTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:            IDColumn,
		ProfileID:     ProfileIDColumn,
		CompanyID:     CompanyIDColumn,
		Content:       ContentColumn,
		RatingAreas:   RatingAreasColumn,
		AiSuggestions: AiSuggestionsColumn,
		CreatedAt:     CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
