//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Holidays = newHolidaysTable("public", "holidays", "")

type holidaysTable struct {
	postgres.Table

	// Columns
	ID          postgres.ColumnString
	CompanyID   postgres.ColumnString
	Name        postgres.ColumnString
	Date        postgres.ColumnDate
	IsRecurring postgres.ColumnBool
	CreatedAt   postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type HolidaysTable struct {
	holidaysTable

	EXCLUDED holidaysTable
}

// AS creates new HolidaysTable with assigned alias
func (a HolidaysTable) AS(alias string) *HolidaysTable {
	return newHolidaysTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new HolidaysTable with assigned schema name
func (a HolidaysTable) FromSchema(schemaName string) *HolidaysTable {
	return newHolidaysTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new HolidaysTable with assigned table prefix
func (a HolidaysTable) WithPrefix(prefix string) *HolidaysTable {
	return newHolidaysTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new HolidaysTable with assigned table suffix
func (a HolidaysTable) WithSuffix(suffix string) *HolidaysTable {
	return newHolidaysTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newHolidaysTable(schemaName, tableName, alias string) *HolidaysTable {
	return &HolidaysTable{
		holidaysTable: newHolidaysTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newHolidaysTableImpl("", "excluded", ""),
	}
}

func newHolidaysTableImpl(schemaName, tableName, alias string) holidaysTable {
	var (
		IDColumn          = postgres.StringColumn("id")
		CompanyIDColumn   = postgres.StringColumn("company_id")
		NameColumn        = postgres.StringColumn("name")
		DateColumn        = postgres.DateColumn("date")
		IsRecurringColumn = postgres.BoolColumn("is_recurring")
		CreatedAtColumn   = postgres.TimestampzColumn("created_at")
		allColumns        = postgres.ColumnList{IDColumn, CompanyIDColumn, NameColumn, DateColumn, IsRecurringColumn, CreatedAtColumn}
		mutableColumns    = postgres.ColumnList{CompanyIDColumn, NameColumn, DateColumn, IsRecurringColumn, CreatedAtColumn}
		defaultColumns    = postgres.ColumnList{IDColumn, IsRecurringColumn, CreatedAtColumn}
	)

	return holidaysTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		CompanyID:   CompanyIDColumn,
		Name:        NameColumn,
		Date:        DateColumn,
		IsRecurring: IsRecurringColumn,
		CreatedAt:   CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
