//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var HrAnalyticsSnapshots = newHrAnalyticsSnapshotsTable("public", "hr_analytics_snapshots", "")

type hrAnalyticsSnapshotsTable struct {
	postgres.Table

	// Columns
	ID                  postgres.ColumnString
	CompanyID           postgres.ColumnString
	SnapshotMonth       postgres.ColumnDate
	TotalHeadcount      postgres.ColumnInteger
	NewHires            postgres.ColumnInteger
	Terminations        postgres.ColumnInteger
	TurnoverRate        postgres.ColumnFloat
	AvgTenureMonths     postgres.ColumnFloat
	DepartmentBreakdown postgres.ColumnString
	CreatedAt           postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type HrAnalyticsSnapshotsTable struct {
	hrAnalyticsSnapshotsTable

	EXCLUDED hrAnalyticsSnapshotsTable
}

// AS creates new HrAnalyticsSnapshotsTable with assigned alias
func (a HrAnalyticsSnapshotsTable) AS(alias string) *HrAnalyticsSnapshotsTable {
	return newHrAnalyticsSnapshotsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new HrAnalyticsSnapshotsTable with assigned schema name
func (a HrAnalyticsSnapshotsTable) FromSchema(schemaName string) *HrAnalyticsSnapshotsTable {
	return newHrAnalyticsSnapshotsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new HrAnalyticsSnapshotsTable with assigned table prefix
func (a HrAnalyticsSnapshotsTable) WithPrefix(prefix string) *HrAnalyticsSnapshotsTable {
	return newHrAnalyticsSnapshotsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new HrAnalyticsSnapshotsTable with assigned table suffix
func (a HrAnalyticsSnapshotsTable) WithSuffix(suffix string) *HrAnalyticsSnapshotsTable {
	return newHrAnalyticsSnapshotsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newHrAnalyticsSnapshotsTable(schemaName, tableName, alias string) *HrAnalyticsSnapshotsTable {
	return &HrAnalyticsSnapshotsTable{
		hrAnalyticsSnapshotsTable: newHrAnalyticsSnapshotsTableImpl(schemaName, tableName, alias),
		EXCLUDED:                  newHrAnalyticsSnapshotsTableImpl("", "excluded", ""),
	}
}

func newHrAnalyticsSnapshotsTableImpl(schemaName, tableName, alias string) hrAnalyticsSnapshotsTable {
	var (
		IDColumn                  = postgres.StringColumn("id")
		CompanyIDColumn           = postgres.StringColumn("company_id")
		SnapshotMonthColumn       = postgres.DateColumn("snapshot_month")
		TotalHeadcountColumn      = postgres.IntegerColumn("total_headcount")
		NewHiresColumn            = postgres.IntegerColumn("new_hires")
		TerminationsColumn        = postgres.IntegerColumn("terminations")
		TurnoverRateColumn        = postgres.FloatColumn("turnover_rate")
		AvgTenureMonthsColumn     = postgres.FloatColumn("avg_tenure_months")
		DepartmentBreakdownColumn = postgres.StringColumn("department_breakdown")
		CreatedAtColumn           = postgres.TimestampzColumn("created_at")
		allColumns                = postgres.ColumnList{IDColumn, CompanyIDColumn, SnapshotMonthColumn, TotalHeadcountColumn, NewHiresColumn, TerminationsColumn, TurnoverRateColumn, AvgTenureMonthsColumn, DepartmentBreakdownColumn, CreatedAtColumn}
		mutableColumns            = postgres.ColumnList{CompanyIDColumn, SnapshotMonthColumn, TotalHeadcountColumn, NewHiresColumn, TerminationsColumn, TurnoverRateColumn, AvgTenureMonthsColumn, DepartmentBreakdownColumn, CreatedAtColumn}
		defaultColumns            = postgres.ColumnList{IDColumn, TotalHeadcountColumn, NewHiresColumn, TerminationsColumn, TurnoverRateColumn, AvgTenureMonthsColumn, DepartmentBreakdownColumn, CreatedAtColumn}
	)

	return hrAnalyticsSnapshotsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                  IDColumn,
		CompanyID:           CompanyIDColumn,
		SnapshotMonth:       SnapshotMonthColumn,
		TotalHeadcount:      TotalHeadcountColumn,
		NewHires:            NewHiresColumn,
		Terminations:        TerminationsColumn,
		TurnoverRate:        TurnoverRateColumn,
		AvgTenureMonths:     AvgTenureMonthsColumn,
		DepartmentBreakdown: DepartmentBreakdownColumn,
		CreatedAt:           CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
