//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var HrisRoles = newHrisRolesTable("public", "hris_roles", "")

type hrisRolesTable struct {
	postgres.Table

	// Columns
	ID          postgres.ColumnString
	CompanyID   postgres.ColumnString
	Name        postgres.ColumnString
	Description postgres.ColumnString
	IsSystem    postgres.ColumnBool
	CreatedAt   postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type HrisRolesTable struct {
	hrisRolesTable

	EXCLUDED hrisRolesTable
}

// AS creates new HrisRolesTable with assigned alias
func (a HrisRolesTable) AS(alias string) *HrisRolesTable {
	return newHrisRolesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new HrisRolesTable with assigned schema name
func (a HrisRolesTable) FromSchema(schemaName string) *HrisRolesTable {
	return newHrisRolesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new HrisRolesTable with assigned table prefix
func (a HrisRolesTable) WithPrefix(prefix string) *HrisRolesTable {
	return newHrisRolesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new HrisRolesTable with assigned table suffix
func (a HrisRolesTable) WithSuffix(suffix string) *HrisRolesTable {
	return newHrisRolesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newHrisRolesTable(schemaName, tableName, alias string) *HrisRolesTable {
	return &HrisRolesTable{
		hrisRolesTable: newHrisRolesTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newHrisRolesTableImpl("", "excluded", ""),
	}
}

func newHrisRolesTableImpl(schemaName, tableName, alias string) hrisRolesTable {
	var (
		IDColumn          = postgres.StringColumn("id")
		CompanyIDColumn   = postgres.StringColumn("company_id")
		NameColumn        = postgres.StringColumn("name")
		DescriptionColumn = postgres.StringColumn("description")
		IsSystemColumn    = postgres.BoolColumn("is_system")
		CreatedAtColumn   = postgres.TimestampzColumn("created_at")
		allColumns        = postgres.ColumnList{IDColumn, CompanyIDColumn, NameColumn, DescriptionColumn, IsSystemColumn, CreatedAtColumn}
		mutableColumns    = postgres.ColumnList{CompanyIDColumn, NameColumn, DescriptionColumn, IsSystemColumn, CreatedAtColumn}
		defaultColumns    = postgres.ColumnList{IDColumn, IsSystemColumn, CreatedAtColumn}
	)

	return hrisRolesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		CompanyID:   CompanyIDColumn,
		Name:        NameColumn,
		Description: DescriptionColumn,
		IsSystem:    IsSystemColumn,
		CreatedAt:   CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
