//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var IndustryCategories = newIndustryCategoriesTable("public", "industry_categories", "")

type industryCategoriesTable struct {
	postgres.Table

	// Columns
	ID          postgres.ColumnString
	Name        postgres.ColumnString
	Description postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type IndustryCategoriesTable struct {
	industryCategoriesTable

	EXCLUDED industryCategoriesTable
}

// AS creates new IndustryCategoriesTable with assigned alias
func (a IndustryCategoriesTable) AS(alias string) *IndustryCategoriesTable {
	return newIndustryCategoriesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new IndustryCategoriesTable with assigned schema name
func (a IndustryCategoriesTable) FromSchema(schemaName string) *IndustryCategoriesTable {
	return newIndustryCategoriesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new IndustryCategoriesTable with assigned table prefix
func (a IndustryCategoriesTable) WithPrefix(prefix string) *IndustryCategoriesTable {
	return newIndustryCategoriesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new IndustryCategoriesTable with assigned table suffix
func (a IndustryCategoriesTable) WithSuffix(suffix string) *IndustryCategoriesTable {
	return newIndustryCategoriesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newIndustryCategoriesTable(schemaName, tableName, alias string) *IndustryCategoriesTable {
	return &IndustryCategoriesTable{
		industryCategoriesTable: newIndustryCategoriesTableImpl(schemaName, tableName, alias),
		EXCLUDED:                newIndustryCategoriesTableImpl("", "excluded", ""),
	}
}

func newIndustryCategoriesTableImpl(schemaName, tableName, alias string) industryCategoriesTable {
	var (
		IDColumn          = postgres.StringColumn("id")
		NameColumn        = postgres.StringColumn("name")
		DescriptionColumn = postgres.StringColumn("description")
		allColumns        = postgres.ColumnList{IDColumn, NameColumn, DescriptionColumn}
		mutableColumns    = postgres.ColumnList{NameColumn, DescriptionColumn}
		defaultColumns    = postgres.ColumnList{IDColumn}
	)

	return industryCategoriesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		Name:        NameColumn,
		Description: DescriptionColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
