//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var JobExperiences = newJobExperiencesTable("public", "job_experiences", "")

type jobExperiencesTable struct {
	postgres.Table

	// Columns
	ID           postgres.ColumnString
	ProfileID    postgres.ColumnString
	Type         postgres.ColumnString
	Title        postgres.ColumnString
	Organization postgres.ColumnString
	StartDate    postgres.ColumnString
	EndDate      postgres.ColumnString
	IsCurrent    postgres.ColumnBool
	Description  postgres.ColumnString
	Industry     postgres.ColumnString
	SkillsUsed   postgres.ColumnStringArray
	URL          postgres.ColumnString
	SortOrder    postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type JobExperiencesTable struct {
	jobExperiencesTable

	EXCLUDED jobExperiencesTable
}

// AS creates new JobExperiencesTable with assigned alias
func (a JobExperiencesTable) AS(alias string) *JobExperiencesTable {
	return newJobExperiencesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new JobExperiencesTable with assigned schema name
func (a JobExperiencesTable) FromSchema(schemaName string) *JobExperiencesTable {
	return newJobExperiencesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new JobExperiencesTable with assigned table prefix
func (a JobExperiencesTable) WithPrefix(prefix string) *JobExperiencesTable {
	return newJobExperiencesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new JobExperiencesTable with assigned table suffix
func (a JobExperiencesTable) WithSuffix(suffix string) *JobExperiencesTable {
	return newJobExperiencesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newJobExperiencesTable(schemaName, tableName, alias string) *JobExperiencesTable {
	return &JobExperiencesTable{
		jobExperiencesTable: newJobExperiencesTableImpl(schemaName, tableName, alias),
		EXCLUDED:            newJobExperiencesTableImpl("", "excluded", ""),
	}
}

func newJobExperiencesTableImpl(schemaName, tableName, alias string) jobExperiencesTable {
	var (
		IDColumn           = postgres.StringColumn("id")
		ProfileIDColumn    = postgres.StringColumn("profile_id")
		TypeColumn         = postgres.StringColumn("type")
		TitleColumn        = postgres.StringColumn("title")
		OrganizationColumn = postgres.StringColumn("organization")
		StartDateColumn    = postgres.StringColumn("start_date")
		EndDateColumn      = postgres.StringColumn("end_date")
		IsCurrentColumn    = postgres.BoolColumn("is_current")
		DescriptionColumn  = postgres.StringColumn("description")
		IndustryColumn     = postgres.StringColumn("industry")
		SkillsUsedColumn   = postgres.StringArrayColumn("skills_used")
		URLColumn          = postgres.StringColumn("url")
		SortOrderColumn    = postgres.IntegerColumn("sort_order")
		allColumns         = postgres.ColumnList{IDColumn, ProfileIDColumn, TypeColumn, TitleColumn, OrganizationColumn, StartDateColumn, EndDateColumn, IsCurrentColumn, DescriptionColumn, IndustryColumn, SkillsUsedColumn, URLColumn, SortOrderColumn}
		mutableColumns     = postgres.ColumnList{ProfileIDColumn, TypeColumn, TitleColumn, OrganizationColumn, StartDateColumn, EndDateColumn, IsCurrentColumn, DescriptionColumn, IndustryColumn, SkillsUsedColumn, URLColumn, SortOrderColumn}
		defaultColumns     = postgres.ColumnList{IDColumn, IsCurrentColumn, SortOrderColumn}
	)

	return jobExperiencesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		ProfileID:    ProfileIDColumn,
		Type:         TypeColumn,
		Title:        TitleColumn,
		Organization: OrganizationColumn,
		StartDate:    StartDateColumn,
		EndDate:      EndDateColumn,
		IsCurrent:    IsCurrentColumn,
		Description:  DescriptionColumn,
		Industry:     IndustryColumn,
		SkillsUsed:   SkillsUsedColumn,
		URL:          URLColumn,
		SortOrder:    SortOrderColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
