//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var JobPostings = newJobPostingsTable("public", "job_postings", "")

type jobPostingsTable struct {
	postgres.Table

	// Columns
	ID              postgres.ColumnString
	CompanyID       postgres.ColumnString
	Title           postgres.ColumnString
	Description     postgres.ColumnString
	Industry        postgres.ColumnString
	Tags            postgres.ColumnStringArray
	RequiredSkills  postgres.ColumnStringArray
	ExperienceLevel postgres.ColumnString
	Location        postgres.ColumnString
	SalaryRange     postgres.ColumnString
	Status          postgres.ColumnString
	CreatedAt       postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type JobPostingsTable struct {
	jobPostingsTable

	EXCLUDED jobPostingsTable
}

// AS creates new JobPostingsTable with assigned alias
func (a JobPostingsTable) AS(alias string) *JobPostingsTable {
	return newJobPostingsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new JobPostingsTable with assigned schema name
func (a JobPostingsTable) FromSchema(schemaName string) *JobPostingsTable {
	return newJobPostingsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new JobPostingsTable with assigned table prefix
func (a JobPostingsTable) WithPrefix(prefix string) *JobPostingsTable {
	return newJobPostingsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new JobPostingsTable with assigned table suffix
func (a JobPostingsTable) WithSuffix(suffix string) *JobPostingsTable {
	return newJobPostingsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newJobPostingsTable(schemaName, tableName, alias string) *JobPostingsTable {
	return &JobPostingsTable{
		jobPostingsTable: newJobPostingsTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newJobPostingsTableImpl("", "excluded", ""),
	}
}

func newJobPostingsTableImpl(schemaName, tableName, alias string) jobPostingsTable {
	var (
		IDColumn              = postgres.StringColumn("id")
		CompanyIDColumn       = postgres.StringColumn("company_id")
		TitleColumn           = postgres.StringColumn("title")
		DescriptionColumn     = postgres.StringColumn("description")
		IndustryColumn        = postgres.StringColumn("industry")
		TagsColumn            = postgres.StringArrayColumn("tags")
		RequiredSkillsColumn  = postgres.StringArrayColumn("required_skills")
		ExperienceLevelColumn = postgres.StringColumn("experience_level")
		LocationColumn        = postgres.StringColumn("location")
		SalaryRangeColumn     = postgres.StringColumn("salary_range")
		StatusColumn          = postgres.StringColumn("status")
		CreatedAtColumn       = postgres.TimestampzColumn("created_at")
		allColumns            = postgres.ColumnList{IDColumn, CompanyIDColumn, TitleColumn, DescriptionColumn, IndustryColumn, TagsColumn, RequiredSkillsColumn, ExperienceLevelColumn, LocationColumn, SalaryRangeColumn, StatusColumn, CreatedAtColumn}
		mutableColumns        = postgres.ColumnList{CompanyIDColumn, TitleColumn, DescriptionColumn, IndustryColumn, TagsColumn, RequiredSkillsColumn, ExperienceLevelColumn, LocationColumn, SalaryRangeColumn, StatusColumn, CreatedAtColumn}
		defaultColumns        = postgres.ColumnList{IDColumn, StatusColumn, CreatedAtColumn}
	)

	return jobPostingsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:              IDColumn,
		CompanyID:       CompanyIDColumn,
		Title:           TitleColumn,
		Description:     DescriptionColumn,
		Industry:        IndustryColumn,
		Tags:            TagsColumn,
		RequiredSkills:  RequiredSkillsColumn,
		ExperienceLevel: ExperienceLevelColumn,
		Location:        LocationColumn,
		SalaryRange:     SalaryRangeColumn,
		Status:          StatusColumn,
		CreatedAt:       CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
