//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var JobCategoryWeights = newJobCategoryWeightsTable("public", "job_category_weights", "")

type jobCategoryWeightsTable struct {
	postgres.Table

	// Columns
	ID           postgres.ColumnString
	JobPostingID postgres.ColumnString
	CategoryID   postgres.ColumnString
	Weight       postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type JobCategoryWeightsTable struct {
	jobCategoryWeightsTable

	EXCLUDED jobCategoryWeightsTable
}

// AS creates new JobCategoryWeightsTable with assigned alias
func (a JobCategoryWeightsTable) AS(alias string) *JobCategoryWeightsTable {
	return newJobCategoryWeightsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new JobCategoryWeightsTable with assigned schema name
func (a JobCategoryWeightsTable) FromSchema(schemaName string) *JobCategoryWeightsTable {
	return newJobCategoryWeightsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new JobCategoryWeightsTable with assigned table prefix
func (a JobCategoryWeightsTable) WithPrefix(prefix string) *JobCategoryWeightsTable {
	return newJobCategoryWeightsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new JobCategoryWeightsTable with assigned table suffix
func (a JobCategoryWeightsTable) WithSuffix(suffix string) *JobCategoryWeightsTable {
	return newJobCategoryWeightsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newJobCategoryWeightsTable(schemaName, tableName, alias string) *JobCategoryWeightsTable {
	return &JobCategoryWeightsTable{
		jobCategoryWeightsTable: newJobCategoryWeightsTableImpl(schemaName, tableName, alias),
		EXCLUDED:                newJobCategoryWeightsTableImpl("", "excluded", ""),
	}
}

func newJobCategoryWeightsTableImpl(schemaName, tableName, alias string) jobCategoryWeightsTable {
	var (
		IDColumn           = postgres.StringColumn("id")
		JobPostingIDColumn = postgres.StringColumn("job_posting_id")
		CategoryIDColumn   = postgres.StringColumn("category_id")
		WeightColumn       = postgres.IntegerColumn("weight")
		allColumns         = postgres.ColumnList{IDColumn, JobPostingIDColumn, CategoryIDColumn, WeightColumn}
		mutableColumns     = postgres.ColumnList{JobPostingIDColumn, CategoryIDColumn, WeightColumn}
		defaultColumns     = postgres.ColumnList{IDColumn, WeightColumn}
	)

	return jobCategoryWeightsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		JobPostingID: JobPostingIDColumn,
		CategoryID:   CategoryIDColumn,
		Weight:       WeightColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
