//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var JobseekerProfiles = newJobseekerProfilesTable("public", "jobseeker_profiles", "")

type jobseekerProfilesTable struct {
	postgres.Table

	// Columns
	ID                postgres.ColumnString
	UserID            postgres.ColumnString
	Headline          postgres.ColumnString
	About             postgres.ColumnString
	YearsOfExperience postgres.ColumnInteger
	Slug              postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type JobseekerProfilesTable struct {
	jobseekerProfilesTable

	EXCLUDED jobseekerProfilesTable
}

// AS creates new JobseekerProfilesTable with assigned alias
func (a JobseekerProfilesTable) AS(alias string) *JobseekerProfilesTable {
	return newJobseekerProfilesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new JobseekerProfilesTable with assigned schema name
func (a JobseekerProfilesTable) FromSchema(schemaName string) *JobseekerProfilesTable {
	return newJobseekerProfilesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new JobseekerProfilesTable with assigned table prefix
func (a JobseekerProfilesTable) WithPrefix(prefix string) *JobseekerProfilesTable {
	return newJobseekerProfilesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new JobseekerProfilesTable with assigned table suffix
func (a JobseekerProfilesTable) WithSuffix(suffix string) *JobseekerProfilesTable {
	return newJobseekerProfilesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newJobseekerProfilesTable(schemaName, tableName, alias string) *JobseekerProfilesTable {
	return &JobseekerProfilesTable{
		jobseekerProfilesTable: newJobseekerProfilesTableImpl(schemaName, tableName, alias),
		EXCLUDED:               newJobseekerProfilesTableImpl("", "excluded", ""),
	}
}

func newJobseekerProfilesTableImpl(schemaName, tableName, alias string) jobseekerProfilesTable {
	var (
		IDColumn                = postgres.StringColumn("id")
		UserIDColumn            = postgres.StringColumn("user_id")
		HeadlineColumn          = postgres.StringColumn("headline")
		AboutColumn             = postgres.StringColumn("about")
		YearsOfExperienceColumn = postgres.IntegerColumn("years_of_experience")
		SlugColumn              = postgres.StringColumn("slug")
		allColumns              = postgres.ColumnList{IDColumn, UserIDColumn, HeadlineColumn, AboutColumn, YearsOfExperienceColumn, SlugColumn}
		mutableColumns          = postgres.ColumnList{UserIDColumn, HeadlineColumn, AboutColumn, YearsOfExperienceColumn, SlugColumn}
		defaultColumns          = postgres.ColumnList{IDColumn}
	)

	return jobseekerProfilesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                IDColumn,
		UserID:            UserIDColumn,
		Headline:          HeadlineColumn,
		About:             AboutColumn,
		YearsOfExperience: YearsOfExperienceColumn,
		Slug:              SlugColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
