//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var LeaveBalances = newLeaveBalancesTable("public", "leave_balances", "")

type leaveBalancesTable struct {
	postgres.Table

	// Columns
	ID            postgres.ColumnString
	EmployeeID    postgres.ColumnString
	LeaveTypeID   postgres.ColumnString
	Year          postgres.ColumnInteger
	TotalDays     postgres.ColumnInteger
	UsedDays      postgres.ColumnInteger
	CarryOverDays postgres.ColumnInteger
	CreatedAt     postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type LeaveBalancesTable struct {
	leaveBalancesTable

	EXCLUDED leaveBalancesTable
}

// AS creates new LeaveBalancesTable with assigned alias
func (a LeaveBalancesTable) AS(alias string) *LeaveBalancesTable {
	return newLeaveBalancesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new LeaveBalancesTable with assigned schema name
func (a LeaveBalancesTable) FromSchema(schemaName string) *LeaveBalancesTable {
	return newLeaveBalancesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new LeaveBalancesTable with assigned table prefix
func (a LeaveBalancesTable) WithPrefix(prefix string) *LeaveBalancesTable {
	return newLeaveBalancesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new LeaveBalancesTable with assigned table suffix
func (a LeaveBalancesTable) WithSuffix(suffix string) *LeaveBalancesTable {
	return newLeaveBalancesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newLeaveBalancesTable(schemaName, tableName, alias string) *LeaveBalancesTable {
	return &LeaveBalancesTable{
		leaveBalancesTable: newLeaveBalancesTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newLeaveBalancesTableImpl("", "excluded", ""),
	}
}

func newLeaveBalancesTableImpl(schemaName, tableName, alias string) leaveBalancesTable {
	var (
		IDColumn            = postgres.StringColumn("id")
		EmployeeIDColumn    = postgres.StringColumn("employee_id")
		LeaveTypeIDColumn   = postgres.StringColumn("leave_type_id")
		YearColumn          = postgres.IntegerColumn("year")
		TotalDaysColumn     = postgres.IntegerColumn("total_days")
		UsedDaysColumn      = postgres.IntegerColumn("used_days")
		CarryOverDaysColumn = postgres.IntegerColumn("carry_over_days")
		CreatedAtColumn     = postgres.TimestampzColumn("created_at")
		allColumns          = postgres.ColumnList{IDColumn, EmployeeIDColumn, LeaveTypeIDColumn, YearColumn, TotalDaysColumn, UsedDaysColumn, CarryOverDaysColumn, CreatedAtColumn}
		mutableColumns      = postgres.ColumnList{EmployeeIDColumn, LeaveTypeIDColumn, YearColumn, TotalDaysColumn, UsedDaysColumn, CarryOverDaysColumn, CreatedAtColumn}
		defaultColumns      = postgres.ColumnList{IDColumn, TotalDaysColumn, UsedDaysColumn, CarryOverDaysColumn, CreatedAtColumn}
	)

	return leaveBalancesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:            IDColumn,
		EmployeeID:    EmployeeIDColumn,
		LeaveTypeID:   LeaveTypeIDColumn,
		Year:          YearColumn,
		TotalDays:     TotalDaysColumn,
		UsedDays:      UsedDaysColumn,
		CarryOverDays: CarryOverDaysColumn,
		CreatedAt:     CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
