//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var LeaveTypes = newLeaveTypesTable("public", "leave_types", "")

type leaveTypesTable struct {
	postgres.Table

	// Columns
	ID                 postgres.ColumnString
	CompanyID          postgres.ColumnString
	Name               postgres.ColumnString
	Code               postgres.ColumnString
	DefaultDaysPerYear postgres.ColumnInteger
	IsPaid             postgres.ColumnBool
	RequiresAttachment postgres.ColumnBool
	IsActive           postgres.ColumnBool
	CreatedAt          postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type LeaveTypesTable struct {
	leaveTypesTable

	EXCLUDED leaveTypesTable
}

// AS creates new LeaveTypesTable with assigned alias
func (a LeaveTypesTable) AS(alias string) *LeaveTypesTable {
	return newLeaveTypesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new LeaveTypesTable with assigned schema name
func (a LeaveTypesTable) FromSchema(schemaName string) *LeaveTypesTable {
	return newLeaveTypesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new LeaveTypesTable with assigned table prefix
func (a LeaveTypesTable) WithPrefix(prefix string) *LeaveTypesTable {
	return newLeaveTypesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new LeaveTypesTable with assigned table suffix
func (a LeaveTypesTable) WithSuffix(suffix string) *LeaveTypesTable {
	return newLeaveTypesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newLeaveTypesTable(schemaName, tableName, alias string) *LeaveTypesTable {
	return &LeaveTypesTable{
		leaveTypesTable: newLeaveTypesTableImpl(schemaName, tableName, alias),
		EXCLUDED:        newLeaveTypesTableImpl("", "excluded", ""),
	}
}

func newLeaveTypesTableImpl(schemaName, tableName, alias string) leaveTypesTable {
	var (
		IDColumn                 = postgres.StringColumn("id")
		CompanyIDColumn          = postgres.StringColumn("company_id")
		NameColumn               = postgres.StringColumn("name")
		CodeColumn               = postgres.StringColumn("code")
		DefaultDaysPerYearColumn = postgres.IntegerColumn("default_days_per_year")
		IsPaidColumn             = postgres.BoolColumn("is_paid")
		RequiresAttachmentColumn = postgres.BoolColumn("requires_attachment")
		IsActiveColumn           = postgres.BoolColumn("is_active")
		CreatedAtColumn          = postgres.TimestampzColumn("created_at")
		allColumns               = postgres.ColumnList{IDColumn, CompanyIDColumn, NameColumn, CodeColumn, DefaultDaysPerYearColumn, IsPaidColumn, RequiresAttachmentColumn, IsActiveColumn, CreatedAtColumn}
		mutableColumns           = postgres.ColumnList{CompanyIDColumn, NameColumn, CodeColumn, DefaultDaysPerYearColumn, IsPaidColumn, RequiresAttachmentColumn, IsActiveColumn, CreatedAtColumn}
		defaultColumns           = postgres.ColumnList{IDColumn, DefaultDaysPerYearColumn, IsPaidColumn, RequiresAttachmentColumn, IsActiveColumn, CreatedAtColumn}
	)

	return leaveTypesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                 IDColumn,
		CompanyID:          CompanyIDColumn,
		Name:               NameColumn,
		Code:               CodeColumn,
		DefaultDaysPerYear: DefaultDaysPerYearColumn,
		IsPaid:             IsPaidColumn,
		RequiresAttachment: RequiresAttachmentColumn,
		IsActive:           IsActiveColumn,
		CreatedAt:          CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
