//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var LeaveRequests = newLeaveRequestsTable("public", "leave_requests", "")

type leaveRequestsTable struct {
	postgres.Table

	// Columns
	ID              postgres.ColumnString
	CompanyID       postgres.ColumnString
	EmployeeID      postgres.ColumnString
	LeaveTypeID     postgres.ColumnString
	StartDate       postgres.ColumnDate
	EndDate         postgres.ColumnDate
	TotalDays       postgres.ColumnInteger
	Reason          postgres.ColumnString
	AttachmentURL   postgres.ColumnString
	Status          postgres.ColumnString
	ReviewerID      postgres.ColumnString
	ReviewerComment postgres.ColumnString
	ReviewedAt      postgres.ColumnTimestampz
	CreatedAt       postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type LeaveRequestsTable struct {
	leaveRequestsTable

	EXCLUDED leaveRequestsTable
}

// AS creates new LeaveRequestsTable with assigned alias
func (a LeaveRequestsTable) AS(alias string) *LeaveRequestsTable {
	return newLeaveRequestsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new LeaveRequestsTable with assigned schema name
func (a LeaveRequestsTable) FromSchema(schemaName string) *LeaveRequestsTable {
	return newLeaveRequestsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new LeaveRequestsTable with assigned table prefix
func (a LeaveRequestsTable) WithPrefix(prefix string) *LeaveRequestsTable {
	return newLeaveRequestsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new LeaveRequestsTable with assigned table suffix
func (a LeaveRequestsTable) WithSuffix(suffix string) *LeaveRequestsTable {
	return newLeaveRequestsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newLeaveRequestsTable(schemaName, tableName, alias string) *LeaveRequestsTable {
	return &LeaveRequestsTable{
		leaveRequestsTable: newLeaveRequestsTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newLeaveRequestsTableImpl("", "excluded", ""),
	}
}

func newLeaveRequestsTableImpl(schemaName, tableName, alias string) leaveRequestsTable {
	var (
		IDColumn              = postgres.StringColumn("id")
		CompanyIDColumn       = postgres.StringColumn("company_id")
		EmployeeIDColumn      = postgres.StringColumn("employee_id")
		LeaveTypeIDColumn     = postgres.StringColumn("leave_type_id")
		StartDateColumn       = postgres.DateColumn("start_date")
		EndDateColumn         = postgres.DateColumn("end_date")
		TotalDaysColumn       = postgres.IntegerColumn("total_days")
		ReasonColumn          = postgres.StringColumn("reason")
		AttachmentURLColumn   = postgres.StringColumn("attachment_url")
		StatusColumn          = postgres.StringColumn("status")
		ReviewerIDColumn      = postgres.StringColumn("reviewer_id")
		ReviewerCommentColumn = postgres.StringColumn("reviewer_comment")
		ReviewedAtColumn      = postgres.TimestampzColumn("reviewed_at")
		CreatedAtColumn       = postgres.TimestampzColumn("created_at")
		allColumns            = postgres.ColumnList{IDColumn, CompanyIDColumn, EmployeeIDColumn, LeaveTypeIDColumn, StartDateColumn, EndDateColumn, TotalDaysColumn, ReasonColumn, AttachmentURLColumn, StatusColumn, ReviewerIDColumn, ReviewerCommentColumn, ReviewedAtColumn, CreatedAtColumn}
		mutableColumns        = postgres.ColumnList{CompanyIDColumn, EmployeeIDColumn, LeaveTypeIDColumn, StartDateColumn, EndDateColumn, TotalDaysColumn, ReasonColumn, AttachmentURLColumn, StatusColumn, ReviewerIDColumn, ReviewerCommentColumn, ReviewedAtColumn, CreatedAtColumn}
		defaultColumns        = postgres.ColumnList{IDColumn, StatusColumn, CreatedAtColumn}
	)

	return leaveRequestsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:              IDColumn,
		CompanyID:       CompanyIDColumn,
		EmployeeID:      EmployeeIDColumn,
		LeaveTypeID:     LeaveTypeIDColumn,
		StartDate:       StartDateColumn,
		EndDate:         EndDateColumn,
		TotalDays:       TotalDaysColumn,
		Reason:          ReasonColumn,
		AttachmentURL:   AttachmentURLColumn,
		Status:          StatusColumn,
		ReviewerID:      ReviewerIDColumn,
		ReviewerComment: ReviewerCommentColumn,
		ReviewedAt:      ReviewedAtColumn,
		CreatedAt:       CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
