//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var OnboardingTemplateTasks = newOnboardingTemplateTasksTable("public", "onboarding_template_tasks", "")

type onboardingTemplateTasksTable struct {
	postgres.Table

	// Columns
	ID           postgres.ColumnString
	TemplateID   postgres.ColumnString
	Title        postgres.ColumnString
	Description  postgres.ColumnString
	SortOrder    postgres.ColumnInteger
	DueDays      postgres.ColumnInteger
	AssigneeRole postgres.ColumnString
	CreatedAt    postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type OnboardingTemplateTasksTable struct {
	onboardingTemplateTasksTable

	EXCLUDED onboardingTemplateTasksTable
}

// AS creates new OnboardingTemplateTasksTable with assigned alias
func (a OnboardingTemplateTasksTable) AS(alias string) *OnboardingTemplateTasksTable {
	return newOnboardingTemplateTasksTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new OnboardingTemplateTasksTable with assigned schema name
func (a OnboardingTemplateTasksTable) FromSchema(schemaName string) *OnboardingTemplateTasksTable {
	return newOnboardingTemplateTasksTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new OnboardingTemplateTasksTable with assigned table prefix
func (a OnboardingTemplateTasksTable) WithPrefix(prefix string) *OnboardingTemplateTasksTable {
	return newOnboardingTemplateTasksTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new OnboardingTemplateTasksTable with assigned table suffix
func (a OnboardingTemplateTasksTable) WithSuffix(suffix string) *OnboardingTemplateTasksTable {
	return newOnboardingTemplateTasksTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newOnboardingTemplateTasksTable(schemaName, tableName, alias string) *OnboardingTemplateTasksTable {
	return &OnboardingTemplateTasksTable{
		onboardingTemplateTasksTable: newOnboardingTemplateTasksTableImpl(schemaName, tableName, alias),
		EXCLUDED:                     newOnboardingTemplateTasksTableImpl("", "excluded", ""),
	}
}

func newOnboardingTemplateTasksTableImpl(schemaName, tableName, alias string) onboardingTemplateTasksTable {
	var (
		IDColumn           = postgres.StringColumn("id")
		TemplateIDColumn   = postgres.StringColumn("template_id")
		TitleColumn        = postgres.StringColumn("title")
		DescriptionColumn  = postgres.StringColumn("description")
		SortOrderColumn    = postgres.IntegerColumn("sort_order")
		DueDaysColumn      = postgres.IntegerColumn("due_days")
		AssigneeRoleColumn = postgres.StringColumn("assignee_role")
		CreatedAtColumn    = postgres.TimestampzColumn("created_at")
		allColumns         = postgres.ColumnList{IDColumn, TemplateIDColumn, TitleColumn, DescriptionColumn, SortOrderColumn, DueDaysColumn, AssigneeRoleColumn, CreatedAtColumn}
		mutableColumns     = postgres.ColumnList{TemplateIDColumn, TitleColumn, DescriptionColumn, SortOrderColumn, DueDaysColumn, AssigneeRoleColumn, CreatedAtColumn}
		defaultColumns     = postgres.ColumnList{IDColumn, DescriptionColumn, SortOrderColumn, DueDaysColumn, AssigneeRoleColumn, CreatedAtColumn}
	)

	return onboardingTemplateTasksTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		TemplateID:   TemplateIDColumn,
		Title:        TitleColumn,
		Description:  DescriptionColumn,
		SortOrder:    SortOrderColumn,
		DueDays:      DueDaysColumn,
		AssigneeRole: AssigneeRoleColumn,
		CreatedAt:    CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
