//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var OnboardingChecklistItems = newOnboardingChecklistItemsTable("public", "onboarding_checklist_items", "")

type onboardingChecklistItemsTable struct {
	postgres.Table

	// Columns
	ID             postgres.ColumnString
	ChecklistID    postgres.ColumnString
	TemplateTaskID postgres.ColumnString
	Title          postgres.ColumnString
	Description    postgres.ColumnString
	SortOrder      postgres.ColumnInteger
	DueDate        postgres.ColumnDate
	IsCompleted    postgres.ColumnBool
	CompletedAt    postgres.ColumnTimestampz
	CompletedBy    postgres.ColumnString
	Notes          postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type OnboardingChecklistItemsTable struct {
	onboardingChecklistItemsTable

	EXCLUDED onboardingChecklistItemsTable
}

// AS creates new OnboardingChecklistItemsTable with assigned alias
func (a OnboardingChecklistItemsTable) AS(alias string) *OnboardingChecklistItemsTable {
	return newOnboardingChecklistItemsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new OnboardingChecklistItemsTable with assigned schema name
func (a OnboardingChecklistItemsTable) FromSchema(schemaName string) *OnboardingChecklistItemsTable {
	return newOnboardingChecklistItemsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new OnboardingChecklistItemsTable with assigned table prefix
func (a OnboardingChecklistItemsTable) WithPrefix(prefix string) *OnboardingChecklistItemsTable {
	return newOnboardingChecklistItemsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new OnboardingChecklistItemsTable with assigned table suffix
func (a OnboardingChecklistItemsTable) WithSuffix(suffix string) *OnboardingChecklistItemsTable {
	return newOnboardingChecklistItemsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newOnboardingChecklistItemsTable(schemaName, tableName, alias string) *OnboardingChecklistItemsTable {
	return &OnboardingChecklistItemsTable{
		onboardingChecklistItemsTable: newOnboardingChecklistItemsTableImpl(schemaName, tableName, alias),
		EXCLUDED:                      newOnboardingChecklistItemsTableImpl("", "excluded", ""),
	}
}

func newOnboardingChecklistItemsTableImpl(schemaName, tableName, alias string) onboardingChecklistItemsTable {
	var (
		IDColumn             = postgres.StringColumn("id")
		ChecklistIDColumn    = postgres.StringColumn("checklist_id")
		TemplateTaskIDColumn = postgres.StringColumn("template_task_id")
		TitleColumn          = postgres.StringColumn("title")
		DescriptionColumn    = postgres.StringColumn("description")
		SortOrderColumn      = postgres.IntegerColumn("sort_order")
		DueDateColumn        = postgres.DateColumn("due_date")
		IsCompletedColumn    = postgres.BoolColumn("is_completed")
		CompletedAtColumn    = postgres.TimestampzColumn("completed_at")
		CompletedByColumn    = postgres.StringColumn("completed_by")
		NotesColumn          = postgres.StringColumn("notes")
		allColumns           = postgres.ColumnList{IDColumn, ChecklistIDColumn, TemplateTaskIDColumn, TitleColumn, DescriptionColumn, SortOrderColumn, DueDateColumn, IsCompletedColumn, CompletedAtColumn, CompletedByColumn, NotesColumn}
		mutableColumns       = postgres.ColumnList{ChecklistIDColumn, TemplateTaskIDColumn, TitleColumn, DescriptionColumn, SortOrderColumn, DueDateColumn, IsCompletedColumn, CompletedAtColumn, CompletedByColumn, NotesColumn}
		defaultColumns       = postgres.ColumnList{IDColumn, DescriptionColumn, SortOrderColumn, IsCompletedColumn, NotesColumn}
	)

	return onboardingChecklistItemsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:             IDColumn,
		ChecklistID:    ChecklistIDColumn,
		TemplateTaskID: TemplateTaskIDColumn,
		Title:          TitleColumn,
		Description:    DescriptionColumn,
		SortOrder:      SortOrderColumn,
		DueDate:        DueDateColumn,
		IsCompleted:    IsCompletedColumn,
		CompletedAt:    CompletedAtColumn,
		CompletedBy:    CompletedByColumn,
		Notes:          NotesColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
