//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var OnboardingChecklists = newOnboardingChecklistsTable("public", "onboarding_checklists", "")

type onboardingChecklistsTable struct {
	postgres.Table

	// Columns
	ID          postgres.ColumnString
	CompanyID   postgres.ColumnString
	EmployeeID  postgres.ColumnString
	TemplateID  postgres.ColumnString
	Status      postgres.ColumnString
	StartedAt   postgres.ColumnTimestampz
	CompletedAt postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type OnboardingChecklistsTable struct {
	onboardingChecklistsTable

	EXCLUDED onboardingChecklistsTable
}

// AS creates new OnboardingChecklistsTable with assigned alias
func (a OnboardingChecklistsTable) AS(alias string) *OnboardingChecklistsTable {
	return newOnboardingChecklistsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new OnboardingChecklistsTable with assigned schema name
func (a OnboardingChecklistsTable) FromSchema(schemaName string) *OnboardingChecklistsTable {
	return newOnboardingChecklistsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new OnboardingChecklistsTable with assigned table prefix
func (a OnboardingChecklistsTable) WithPrefix(prefix string) *OnboardingChecklistsTable {
	return newOnboardingChecklistsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new OnboardingChecklistsTable with assigned table suffix
func (a OnboardingChecklistsTable) WithSuffix(suffix string) *OnboardingChecklistsTable {
	return newOnboardingChecklistsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newOnboardingChecklistsTable(schemaName, tableName, alias string) *OnboardingChecklistsTable {
	return &OnboardingChecklistsTable{
		onboardingChecklistsTable: newOnboardingChecklistsTableImpl(schemaName, tableName, alias),
		EXCLUDED:                  newOnboardingChecklistsTableImpl("", "excluded", ""),
	}
}

func newOnboardingChecklistsTableImpl(schemaName, tableName, alias string) onboardingChecklistsTable {
	var (
		IDColumn          = postgres.StringColumn("id")
		CompanyIDColumn   = postgres.StringColumn("company_id")
		EmployeeIDColumn  = postgres.StringColumn("employee_id")
		TemplateIDColumn  = postgres.StringColumn("template_id")
		StatusColumn      = postgres.StringColumn("status")
		StartedAtColumn   = postgres.TimestampzColumn("started_at")
		CompletedAtColumn = postgres.TimestampzColumn("completed_at")
		allColumns        = postgres.ColumnList{IDColumn, CompanyIDColumn, EmployeeIDColumn, TemplateIDColumn, StatusColumn, StartedAtColumn, CompletedAtColumn}
		mutableColumns    = postgres.ColumnList{CompanyIDColumn, EmployeeIDColumn, TemplateIDColumn, StatusColumn, StartedAtColumn, CompletedAtColumn}
		defaultColumns    = postgres.ColumnList{IDColumn, StatusColumn, StartedAtColumn}
	)

	return onboardingChecklistsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		CompanyID:   CompanyIDColumn,
		EmployeeID:  EmployeeIDColumn,
		TemplateID:  TemplateIDColumn,
		Status:      StatusColumn,
		StartedAt:   StartedAtColumn,
		CompletedAt: CompletedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
