//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var OnboardingTemplates = newOnboardingTemplatesTable("public", "onboarding_templates", "")

type onboardingTemplatesTable struct {
	postgres.Table

	// Columns
	ID          postgres.ColumnString
	CompanyID   postgres.ColumnString
	Name        postgres.ColumnString
	Description postgres.ColumnString
	IsActive    postgres.ColumnBool
	CreatedAt   postgres.ColumnTimestampz
	UpdatedAt   postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type OnboardingTemplatesTable struct {
	onboardingTemplatesTable

	EXCLUDED onboardingTemplatesTable
}

// AS creates new OnboardingTemplatesTable with assigned alias
func (a OnboardingTemplatesTable) AS(alias string) *OnboardingTemplatesTable {
	return newOnboardingTemplatesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new OnboardingTemplatesTable with assigned schema name
func (a OnboardingTemplatesTable) FromSchema(schemaName string) *OnboardingTemplatesTable {
	return newOnboardingTemplatesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new OnboardingTemplatesTable with assigned table prefix
func (a OnboardingTemplatesTable) WithPrefix(prefix string) *OnboardingTemplatesTable {
	return newOnboardingTemplatesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new OnboardingTemplatesTable with assigned table suffix
func (a OnboardingTemplatesTable) WithSuffix(suffix string) *OnboardingTemplatesTable {
	return newOnboardingTemplatesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newOnboardingTemplatesTable(schemaName, tableName, alias string) *OnboardingTemplatesTable {
	return &OnboardingTemplatesTable{
		onboardingTemplatesTable: newOnboardingTemplatesTableImpl(schemaName, tableName, alias),
		EXCLUDED:                 newOnboardingTemplatesTableImpl("", "excluded", ""),
	}
}

func newOnboardingTemplatesTableImpl(schemaName, tableName, alias string) onboardingTemplatesTable {
	var (
		IDColumn          = postgres.StringColumn("id")
		CompanyIDColumn   = postgres.StringColumn("company_id")
		NameColumn        = postgres.StringColumn("name")
		DescriptionColumn = postgres.StringColumn("description")
		IsActiveColumn    = postgres.BoolColumn("is_active")
		CreatedAtColumn   = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn   = postgres.TimestampzColumn("updated_at")
		allColumns        = postgres.ColumnList{IDColumn, CompanyIDColumn, NameColumn, DescriptionColumn, IsActiveColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns    = postgres.ColumnList{CompanyIDColumn, NameColumn, DescriptionColumn, IsActiveColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns    = postgres.ColumnList{IDColumn, DescriptionColumn, IsActiveColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return onboardingTemplatesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		CompanyID:   CompanyIDColumn,
		Name:        NameColumn,
		Description: DescriptionColumn,
		IsActive:    IsActiveColumn,
		CreatedAt:   CreatedAtColumn,
		UpdatedAt:   UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
