//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var PayrollRuns = newPayrollRunsTable("public", "payroll_runs", "")

type payrollRunsTable struct {
	postgres.Table

	// Columns
	ID              postgres.ColumnString
	CompanyID       postgres.ColumnString
	PeriodStart     postgres.ColumnDate
	PeriodEnd       postgres.ColumnDate
	Status          postgres.ColumnString
	TotalGross      postgres.ColumnFloat
	TotalDeductions postgres.ColumnFloat
	TotalNet        postgres.ColumnFloat
	EmployeeCount   postgres.ColumnInteger
	Notes           postgres.ColumnString
	RunBy           postgres.ColumnString
	ApprovedBy      postgres.ColumnString
	ApprovedAt      postgres.ColumnTimestampz
	CreatedAt       postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type PayrollRunsTable struct {
	payrollRunsTable

	EXCLUDED payrollRunsTable
}

// AS creates new PayrollRunsTable with assigned alias
func (a PayrollRunsTable) AS(alias string) *PayrollRunsTable {
	return newPayrollRunsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PayrollRunsTable with assigned schema name
func (a PayrollRunsTable) FromSchema(schemaName string) *PayrollRunsTable {
	return newPayrollRunsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PayrollRunsTable with assigned table prefix
func (a PayrollRunsTable) WithPrefix(prefix string) *PayrollRunsTable {
	return newPayrollRunsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PayrollRunsTable with assigned table suffix
func (a PayrollRunsTable) WithSuffix(suffix string) *PayrollRunsTable {
	return newPayrollRunsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPayrollRunsTable(schemaName, tableName, alias string) *PayrollRunsTable {
	return &PayrollRunsTable{
		payrollRunsTable: newPayrollRunsTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newPayrollRunsTableImpl("", "excluded", ""),
	}
}

func newPayrollRunsTableImpl(schemaName, tableName, alias string) payrollRunsTable {
	var (
		IDColumn              = postgres.StringColumn("id")
		CompanyIDColumn       = postgres.StringColumn("company_id")
		PeriodStartColumn     = postgres.DateColumn("period_start")
		PeriodEndColumn       = postgres.DateColumn("period_end")
		StatusColumn          = postgres.StringColumn("status")
		TotalGrossColumn      = postgres.FloatColumn("total_gross")
		TotalDeductionsColumn = postgres.FloatColumn("total_deductions")
		TotalNetColumn        = postgres.FloatColumn("total_net")
		EmployeeCountColumn   = postgres.IntegerColumn("employee_count")
		NotesColumn           = postgres.StringColumn("notes")
		RunByColumn           = postgres.StringColumn("run_by")
		ApprovedByColumn      = postgres.StringColumn("approved_by")
		ApprovedAtColumn      = postgres.TimestampzColumn("approved_at")
		CreatedAtColumn       = postgres.TimestampzColumn("created_at")
		allColumns            = postgres.ColumnList{IDColumn, CompanyIDColumn, PeriodStartColumn, PeriodEndColumn, StatusColumn, TotalGrossColumn, TotalDeductionsColumn, TotalNetColumn, EmployeeCountColumn, NotesColumn, RunByColumn, ApprovedByColumn, ApprovedAtColumn, CreatedAtColumn}
		mutableColumns        = postgres.ColumnList{CompanyIDColumn, PeriodStartColumn, PeriodEndColumn, StatusColumn, TotalGrossColumn, TotalDeductionsColumn, TotalNetColumn, EmployeeCountColumn, NotesColumn, RunByColumn, ApprovedByColumn, ApprovedAtColumn, CreatedAtColumn}
		defaultColumns        = postgres.ColumnList{IDColumn, StatusColumn, TotalGrossColumn, TotalDeductionsColumn, TotalNetColumn, EmployeeCountColumn, CreatedAtColumn}
	)

	return payrollRunsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:              IDColumn,
		CompanyID:       CompanyIDColumn,
		PeriodStart:     PeriodStartColumn,
		PeriodEnd:       PeriodEndColumn,
		Status:          StatusColumn,
		TotalGross:      TotalGrossColumn,
		TotalDeductions: TotalDeductionsColumn,
		TotalNet:        TotalNetColumn,
		EmployeeCount:   EmployeeCountColumn,
		Notes:           NotesColumn,
		RunBy:           RunByColumn,
		ApprovedBy:      ApprovedByColumn,
		ApprovedAt:      ApprovedAtColumn,
		CreatedAt:       CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
