//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Payslips = newPayslipsTable("public", "payslips", "")

type payslipsTable struct {
	postgres.Table

	// Columns
	ID              postgres.ColumnString
	PayrollRunID    postgres.ColumnString
	EmployeeID      postgres.ColumnString
	GrossPay        postgres.ColumnFloat
	TotalDeductions postgres.ColumnFloat
	NetPay          postgres.ColumnFloat
	Breakdown       postgres.ColumnString
	CreatedAt       postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type PayslipsTable struct {
	payslipsTable

	EXCLUDED payslipsTable
}

// AS creates new PayslipsTable with assigned alias
func (a PayslipsTable) AS(alias string) *PayslipsTable {
	return newPayslipsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PayslipsTable with assigned schema name
func (a PayslipsTable) FromSchema(schemaName string) *PayslipsTable {
	return newPayslipsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PayslipsTable with assigned table prefix
func (a PayslipsTable) WithPrefix(prefix string) *PayslipsTable {
	return newPayslipsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PayslipsTable with assigned table suffix
func (a PayslipsTable) WithSuffix(suffix string) *PayslipsTable {
	return newPayslipsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPayslipsTable(schemaName, tableName, alias string) *PayslipsTable {
	return &PayslipsTable{
		payslipsTable: newPayslipsTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newPayslipsTableImpl("", "excluded", ""),
	}
}

func newPayslipsTableImpl(schemaName, tableName, alias string) payslipsTable {
	var (
		IDColumn              = postgres.StringColumn("id")
		PayrollRunIDColumn    = postgres.StringColumn("payroll_run_id")
		EmployeeIDColumn      = postgres.StringColumn("employee_id")
		GrossPayColumn        = postgres.FloatColumn("gross_pay")
		TotalDeductionsColumn = postgres.FloatColumn("total_deductions")
		NetPayColumn          = postgres.FloatColumn("net_pay")
		BreakdownColumn       = postgres.StringColumn("breakdown")
		CreatedAtColumn       = postgres.TimestampzColumn("created_at")
		allColumns            = postgres.ColumnList{IDColumn, PayrollRunIDColumn, EmployeeIDColumn, GrossPayColumn, TotalDeductionsColumn, NetPayColumn, BreakdownColumn, CreatedAtColumn}
		mutableColumns        = postgres.ColumnList{PayrollRunIDColumn, EmployeeIDColumn, GrossPayColumn, TotalDeductionsColumn, NetPayColumn, BreakdownColumn, CreatedAtColumn}
		defaultColumns        = postgres.ColumnList{IDColumn, GrossPayColumn, TotalDeductionsColumn, NetPayColumn, BreakdownColumn, CreatedAtColumn}
	)

	return payslipsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:              IDColumn,
		PayrollRunID:    PayrollRunIDColumn,
		EmployeeID:      EmployeeIDColumn,
		GrossPay:        GrossPayColumn,
		TotalDeductions: TotalDeductionsColumn,
		NetPay:          NetPayColumn,
		Breakdown:       BreakdownColumn,
		CreatedAt:       CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
