//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Positions = newPositionsTable("public", "positions", "")

type positionsTable struct {
	postgres.Table

	// Columns
	ID           postgres.ColumnString
	CompanyID    postgres.ColumnString
	Name         postgres.ColumnString
	DepartmentID postgres.ColumnString
	Level        postgres.ColumnString
	CreatedAt    postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type PositionsTable struct {
	positionsTable

	EXCLUDED positionsTable
}

// AS creates new PositionsTable with assigned alias
func (a PositionsTable) AS(alias string) *PositionsTable {
	return newPositionsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PositionsTable with assigned schema name
func (a PositionsTable) FromSchema(schemaName string) *PositionsTable {
	return newPositionsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PositionsTable with assigned table prefix
func (a PositionsTable) WithPrefix(prefix string) *PositionsTable {
	return newPositionsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PositionsTable with assigned table suffix
func (a PositionsTable) WithSuffix(suffix string) *PositionsTable {
	return newPositionsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPositionsTable(schemaName, tableName, alias string) *PositionsTable {
	return &PositionsTable{
		positionsTable: newPositionsTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newPositionsTableImpl("", "excluded", ""),
	}
}

func newPositionsTableImpl(schemaName, tableName, alias string) positionsTable {
	var (
		IDColumn           = postgres.StringColumn("id")
		CompanyIDColumn    = postgres.StringColumn("company_id")
		NameColumn         = postgres.StringColumn("name")
		DepartmentIDColumn = postgres.StringColumn("department_id")
		LevelColumn        = postgres.StringColumn("level")
		CreatedAtColumn    = postgres.TimestampzColumn("created_at")
		allColumns         = postgres.ColumnList{IDColumn, CompanyIDColumn, NameColumn, DepartmentIDColumn, LevelColumn, CreatedAtColumn}
		mutableColumns     = postgres.ColumnList{CompanyIDColumn, NameColumn, DepartmentIDColumn, LevelColumn, CreatedAtColumn}
		defaultColumns     = postgres.ColumnList{IDColumn, LevelColumn, CreatedAtColumn}
	)

	return positionsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		CompanyID:    CompanyIDColumn,
		Name:         NameColumn,
		DepartmentID: DepartmentIDColumn,
		Level:        LevelColumn,
		CreatedAt:    CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
