//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ProfileViews = newProfileViewsTable("public", "profile_views", "")

type profileViewsTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnString
	ProfileID postgres.ColumnString
	CompanyID postgres.ColumnString
	ViewedAt  postgres.ColumnTimestampz
	ViewerID  postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type ProfileViewsTable struct {
	profileViewsTable

	EXCLUDED profileViewsTable
}

// AS creates new ProfileViewsTable with assigned alias
func (a ProfileViewsTable) AS(alias string) *ProfileViewsTable {
	return newProfileViewsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ProfileViewsTable with assigned schema name
func (a ProfileViewsTable) FromSchema(schemaName string) *ProfileViewsTable {
	return newProfileViewsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ProfileViewsTable with assigned table prefix
func (a ProfileViewsTable) WithPrefix(prefix string) *ProfileViewsTable {
	return newProfileViewsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ProfileViewsTable with assigned table suffix
func (a ProfileViewsTable) WithSuffix(suffix string) *ProfileViewsTable {
	return newProfileViewsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newProfileViewsTable(schemaName, tableName, alias string) *ProfileViewsTable {
	return &ProfileViewsTable{
		profileViewsTable: newProfileViewsTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newProfileViewsTableImpl("", "excluded", ""),
	}
}

func newProfileViewsTableImpl(schemaName, tableName, alias string) profileViewsTable {
	var (
		IDColumn        = postgres.StringColumn("id")
		ProfileIDColumn = postgres.StringColumn("profile_id")
		CompanyIDColumn = postgres.StringColumn("company_id")
		ViewedAtColumn  = postgres.TimestampzColumn("viewed_at")
		ViewerIDColumn  = postgres.StringColumn("viewer_id")
		allColumns      = postgres.ColumnList{IDColumn, ProfileIDColumn, CompanyIDColumn, ViewedAtColumn, ViewerIDColumn}
		mutableColumns  = postgres.ColumnList{ProfileIDColumn, CompanyIDColumn, ViewedAtColumn, ViewerIDColumn}
		defaultColumns  = postgres.ColumnList{IDColumn, ViewedAtColumn}
	)

	return profileViewsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		ProfileID: ProfileIDColumn,
		CompanyID: CompanyIDColumn,
		ViewedAt:  ViewedAtColumn,
		ViewerID:  ViewerIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
