//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var SalaryComponents = newSalaryComponentsTable("public", "salary_components", "")

type salaryComponentsTable struct {
	postgres.Table

	// Columns
	ID            postgres.ColumnString
	CompanyID     postgres.ColumnString
	Name          postgres.ColumnString
	Code          postgres.ColumnString
	Type          postgres.ColumnString
	IsTaxable     postgres.ColumnBool
	IsFixed       postgres.ColumnBool
	DefaultAmount postgres.ColumnFloat
	IsActive      postgres.ColumnBool
	CreatedAt     postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type SalaryComponentsTable struct {
	salaryComponentsTable

	EXCLUDED salaryComponentsTable
}

// AS creates new SalaryComponentsTable with assigned alias
func (a SalaryComponentsTable) AS(alias string) *SalaryComponentsTable {
	return newSalaryComponentsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SalaryComponentsTable with assigned schema name
func (a SalaryComponentsTable) FromSchema(schemaName string) *SalaryComponentsTable {
	return newSalaryComponentsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SalaryComponentsTable with assigned table prefix
func (a SalaryComponentsTable) WithPrefix(prefix string) *SalaryComponentsTable {
	return newSalaryComponentsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SalaryComponentsTable with assigned table suffix
func (a SalaryComponentsTable) WithSuffix(suffix string) *SalaryComponentsTable {
	return newSalaryComponentsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSalaryComponentsTable(schemaName, tableName, alias string) *SalaryComponentsTable {
	return &SalaryComponentsTable{
		salaryComponentsTable: newSalaryComponentsTableImpl(schemaName, tableName, alias),
		EXCLUDED:              newSalaryComponentsTableImpl("", "excluded", ""),
	}
}

func newSalaryComponentsTableImpl(schemaName, tableName, alias string) salaryComponentsTable {
	var (
		IDColumn            = postgres.StringColumn("id")
		CompanyIDColumn     = postgres.StringColumn("company_id")
		NameColumn          = postgres.StringColumn("name")
		CodeColumn          = postgres.StringColumn("code")
		TypeColumn          = postgres.StringColumn("type")
		IsTaxableColumn     = postgres.BoolColumn("is_taxable")
		IsFixedColumn       = postgres.BoolColumn("is_fixed")
		DefaultAmountColumn = postgres.FloatColumn("default_amount")
		IsActiveColumn      = postgres.BoolColumn("is_active")
		CreatedAtColumn     = postgres.TimestampzColumn("created_at")
		allColumns          = postgres.ColumnList{IDColumn, CompanyIDColumn, NameColumn, CodeColumn, TypeColumn, IsTaxableColumn, IsFixedColumn, DefaultAmountColumn, IsActiveColumn, CreatedAtColumn}
		mutableColumns      = postgres.ColumnList{CompanyIDColumn, NameColumn, CodeColumn, TypeColumn, IsTaxableColumn, IsFixedColumn, DefaultAmountColumn, IsActiveColumn, CreatedAtColumn}
		defaultColumns      = postgres.ColumnList{IDColumn, IsTaxableColumn, IsFixedColumn, DefaultAmountColumn, IsActiveColumn, CreatedAtColumn}
	)

	return salaryComponentsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:            IDColumn,
		CompanyID:     CompanyIDColumn,
		Name:          NameColumn,
		Code:          CodeColumn,
		Type:          TypeColumn,
		IsTaxable:     IsTaxableColumn,
		IsFixed:       IsFixedColumn,
		DefaultAmount: DefaultAmountColumn,
		IsActive:      IsActiveColumn,
		CreatedAt:     CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
