//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ShiftTemplates = newShiftTemplatesTable("public", "shift_templates", "")

type shiftTemplatesTable struct {
	postgres.Table

	// Columns
	ID                   postgres.ColumnString
	CompanyID            postgres.ColumnString
	Name                 postgres.ColumnString
	StartTime            postgres.ColumnTime
	EndTime              postgres.ColumnTime
	BreakDurationMinutes postgres.ColumnInteger
	LateToleranceMinutes postgres.ColumnInteger
	OvertimeMultiplier   postgres.ColumnFloat
	ApplicableDays       postgres.ColumnIntegerArray
	IsDefault            postgres.ColumnBool
	CreatedAt            postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type ShiftTemplatesTable struct {
	shiftTemplatesTable

	EXCLUDED shiftTemplatesTable
}

// AS creates new ShiftTemplatesTable with assigned alias
func (a ShiftTemplatesTable) AS(alias string) *ShiftTemplatesTable {
	return newShiftTemplatesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ShiftTemplatesTable with assigned schema name
func (a ShiftTemplatesTable) FromSchema(schemaName string) *ShiftTemplatesTable {
	return newShiftTemplatesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ShiftTemplatesTable with assigned table prefix
func (a ShiftTemplatesTable) WithPrefix(prefix string) *ShiftTemplatesTable {
	return newShiftTemplatesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ShiftTemplatesTable with assigned table suffix
func (a ShiftTemplatesTable) WithSuffix(suffix string) *ShiftTemplatesTable {
	return newShiftTemplatesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newShiftTemplatesTable(schemaName, tableName, alias string) *ShiftTemplatesTable {
	return &ShiftTemplatesTable{
		shiftTemplatesTable: newShiftTemplatesTableImpl(schemaName, tableName, alias),
		EXCLUDED:            newShiftTemplatesTableImpl("", "excluded", ""),
	}
}

func newShiftTemplatesTableImpl(schemaName, tableName, alias string) shiftTemplatesTable {
	var (
		IDColumn                   = postgres.StringColumn("id")
		CompanyIDColumn            = postgres.StringColumn("company_id")
		NameColumn                 = postgres.StringColumn("name")
		StartTimeColumn            = postgres.TimeColumn("start_time")
		EndTimeColumn              = postgres.TimeColumn("end_time")
		BreakDurationMinutesColumn = postgres.IntegerColumn("break_duration_minutes")
		LateToleranceMinutesColumn = postgres.IntegerColumn("late_tolerance_minutes")
		OvertimeMultiplierColumn   = postgres.FloatColumn("overtime_multiplier")
		ApplicableDaysColumn       = postgres.IntegerArrayColumn("applicable_days")
		IsDefaultColumn            = postgres.BoolColumn("is_default")
		CreatedAtColumn            = postgres.TimestampzColumn("created_at")
		allColumns                 = postgres.ColumnList{IDColumn, CompanyIDColumn, NameColumn, StartTimeColumn, EndTimeColumn, BreakDurationMinutesColumn, LateToleranceMinutesColumn, OvertimeMultiplierColumn, ApplicableDaysColumn, IsDefaultColumn, CreatedAtColumn}
		mutableColumns             = postgres.ColumnList{CompanyIDColumn, NameColumn, StartTimeColumn, EndTimeColumn, BreakDurationMinutesColumn, LateToleranceMinutesColumn, OvertimeMultiplierColumn, ApplicableDaysColumn, IsDefaultColumn, CreatedAtColumn}
		defaultColumns             = postgres.ColumnList{IDColumn, BreakDurationMinutesColumn, LateToleranceMinutesColumn, OvertimeMultiplierColumn, ApplicableDaysColumn, IsDefaultColumn, CreatedAtColumn}
	)

	return shiftTemplatesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                   IDColumn,
		CompanyID:            CompanyIDColumn,
		Name:                 NameColumn,
		StartTime:            StartTimeColumn,
		EndTime:              EndTimeColumn,
		BreakDurationMinutes: BreakDurationMinutesColumn,
		LateToleranceMinutes: LateToleranceMinutesColumn,
		OvertimeMultiplier:   OvertimeMultiplierColumn,
		ApplicableDays:       ApplicableDaysColumn,
		IsDefault:            IsDefaultColumn,
		CreatedAt:            CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
