//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var SkillCategories = newSkillCategoriesTable("public", "skill_categories", "")

type skillCategoriesTable struct {
	postgres.Table

	// Columns
	ID          postgres.ColumnString
	Name        postgres.ColumnString
	Description postgres.ColumnString
	CreatedAt   postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type SkillCategoriesTable struct {
	skillCategoriesTable

	EXCLUDED skillCategoriesTable
}

// AS creates new SkillCategoriesTable with assigned alias
func (a SkillCategoriesTable) AS(alias string) *SkillCategoriesTable {
	return newSkillCategoriesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SkillCategoriesTable with assigned schema name
func (a SkillCategoriesTable) FromSchema(schemaName string) *SkillCategoriesTable {
	return newSkillCategoriesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SkillCategoriesTable with assigned table prefix
func (a SkillCategoriesTable) WithPrefix(prefix string) *SkillCategoriesTable {
	return newSkillCategoriesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SkillCategoriesTable with assigned table suffix
func (a SkillCategoriesTable) WithSuffix(suffix string) *SkillCategoriesTable {
	return newSkillCategoriesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSkillCategoriesTable(schemaName, tableName, alias string) *SkillCategoriesTable {
	return &SkillCategoriesTable{
		skillCategoriesTable: newSkillCategoriesTableImpl(schemaName, tableName, alias),
		EXCLUDED:             newSkillCategoriesTableImpl("", "excluded", ""),
	}
}

func newSkillCategoriesTableImpl(schemaName, tableName, alias string) skillCategoriesTable {
	var (
		IDColumn          = postgres.StringColumn("id")
		NameColumn        = postgres.StringColumn("name")
		DescriptionColumn = postgres.StringColumn("description")
		CreatedAtColumn   = postgres.TimestampzColumn("created_at")
		allColumns        = postgres.ColumnList{IDColumn, NameColumn, DescriptionColumn, CreatedAtColumn}
		mutableColumns    = postgres.ColumnList{NameColumn, DescriptionColumn, CreatedAtColumn}
		defaultColumns    = postgres.ColumnList{IDColumn, DescriptionColumn, CreatedAtColumn}
	)

	return skillCategoriesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		Name:        NameColumn,
		Description: DescriptionColumn,
		CreatedAt:   CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
