//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var SpDidRecords = newSpDidRecordsTable("public", "sp_did_records", "")

type spDidRecordsTable struct {
	postgres.Table

	// Columns
	ID         postgres.ColumnString
	CompanyID  postgres.ColumnString
	EmployeeID postgres.ColumnString
	DidString  postgres.ColumnString
	Status     postgres.ColumnString
	CreatedAt  postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type SpDidRecordsTable struct {
	spDidRecordsTable

	EXCLUDED spDidRecordsTable
}

// AS creates new SpDidRecordsTable with assigned alias
func (a SpDidRecordsTable) AS(alias string) *SpDidRecordsTable {
	return newSpDidRecordsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SpDidRecordsTable with assigned schema name
func (a SpDidRecordsTable) FromSchema(schemaName string) *SpDidRecordsTable {
	return newSpDidRecordsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SpDidRecordsTable with assigned table prefix
func (a SpDidRecordsTable) WithPrefix(prefix string) *SpDidRecordsTable {
	return newSpDidRecordsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SpDidRecordsTable with assigned table suffix
func (a SpDidRecordsTable) WithSuffix(suffix string) *SpDidRecordsTable {
	return newSpDidRecordsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSpDidRecordsTable(schemaName, tableName, alias string) *SpDidRecordsTable {
	return &SpDidRecordsTable{
		spDidRecordsTable: newSpDidRecordsTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newSpDidRecordsTableImpl("", "excluded", ""),
	}
}

func newSpDidRecordsTableImpl(schemaName, tableName, alias string) spDidRecordsTable {
	var (
		IDColumn         = postgres.StringColumn("id")
		CompanyIDColumn  = postgres.StringColumn("company_id")
		EmployeeIDColumn = postgres.StringColumn("employee_id")
		DidStringColumn  = postgres.StringColumn("did_string")
		StatusColumn     = postgres.StringColumn("status")
		CreatedAtColumn  = postgres.TimestampzColumn("created_at")
		allColumns       = postgres.ColumnList{IDColumn, CompanyIDColumn, EmployeeIDColumn, DidStringColumn, StatusColumn, CreatedAtColumn}
		mutableColumns   = postgres.ColumnList{CompanyIDColumn, EmployeeIDColumn, DidStringColumn, StatusColumn, CreatedAtColumn}
		defaultColumns   = postgres.ColumnList{IDColumn, StatusColumn, CreatedAtColumn}
	)

	return spDidRecordsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:         IDColumn,
		CompanyID:  CompanyIDColumn,
		EmployeeID: EmployeeIDColumn,
		DidString:  DidStringColumn,
		Status:     StatusColumn,
		CreatedAt:  CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
