//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	AdminAuditLog = AdminAuditLog.FromSchema(schema)
	AiEvaluations = AiEvaluations.FromSchema(schema)
	ApplicationMessages = ApplicationMessages.FromSchema(schema)
	Applications = Applications.FromSchema(schema)
	AttendanceExceptions = AttendanceExceptions.FromSchema(schema)
	AttendanceLogs = AttendanceLogs.FromSchema(schema)
	Branches = Branches.FromSchema(schema)
	CareerPaths = CareerPaths.FromSchema(schema)
	Companies = Companies.FromSchema(schema)
	CompanyReviews = CompanyReviews.FromSchema(schema)
	CompanyWebhooks = CompanyWebhooks.FromSchema(schema)
	Departments = Departments.FromSchema(schema)
	EmailVerificationTokens = EmailVerificationTokens.FromSchema(schema)
	EmployeeIDConfigs = EmployeeIDConfigs.FromSchema(schema)
	EmployeeRoles = EmployeeRoles.FromSchema(schema)
	EmployeeSalary = EmployeeSalary.FromSchema(schema)
	EmployeeShifts = EmployeeShifts.FromSchema(schema)
	Employees = Employees.FromSchema(schema)
	Feedback = Feedback.FromSchema(schema)
	Holidays = Holidays.FromSchema(schema)
	HrAnalyticsSnapshots = HrAnalyticsSnapshots.FromSchema(schema)
	HrisRoles = HrisRoles.FromSchema(schema)
	IndustryCategories = IndustryCategories.FromSchema(schema)
	JobExperiences = JobExperiences.FromSchema(schema)
	JobPostings = JobPostings.FromSchema(schema)
	JobseekerProfiles = JobseekerProfiles.FromSchema(schema)
	LeaveBalances = LeaveBalances.FromSchema(schema)
	LeaveRequests = LeaveRequests.FromSchema(schema)
	LeaveTypes = LeaveTypes.FromSchema(schema)
	Notifications = Notifications.FromSchema(schema)
	OnboardingChecklistItems = OnboardingChecklistItems.FromSchema(schema)
	OnboardingChecklists = OnboardingChecklists.FromSchema(schema)
	OnboardingTemplateTasks = OnboardingTemplateTasks.FromSchema(schema)
	OnboardingTemplates = OnboardingTemplates.FromSchema(schema)
	PasswordResetTokens = PasswordResetTokens.FromSchema(schema)
	PayrollRuns = PayrollRuns.FromSchema(schema)
	Payslips = Payslips.FromSchema(schema)
	Permissions = Permissions.FromSchema(schema)
	Positions = Positions.FromSchema(schema)
	ProfileViews = ProfileViews.FromSchema(schema)
	RefreshTokens = RefreshTokens.FromSchema(schema)
	RolePermissions = RolePermissions.FromSchema(schema)
	SalaryComponents = SalaryComponents.FromSchema(schema)
	SchemaMigrations = SchemaMigrations.FromSchema(schema)
	ShiftTemplates = ShiftTemplates.FromSchema(schema)
	SpDidRecords = SpDidRecords.FromSchema(schema)
	Tags = Tags.FromSchema(schema)
	Users = Users.FromSchema(schema)
	WorkingCalendars = WorkingCalendars.FromSchema(schema)
}
