//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var WorkingCalendars = newWorkingCalendarsTable("public", "working_calendars", "")

type workingCalendarsTable struct {
	postgres.Table

	// Columns
	ID              postgres.ColumnString
	CompanyID       postgres.ColumnString
	BranchID        postgres.ColumnString
	Year            postgres.ColumnInteger
	DefaultWorkDays postgres.ColumnIntegerArray
	CreatedAt       postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type WorkingCalendarsTable struct {
	workingCalendarsTable

	EXCLUDED workingCalendarsTable
}

// AS creates new WorkingCalendarsTable with assigned alias
func (a WorkingCalendarsTable) AS(alias string) *WorkingCalendarsTable {
	return newWorkingCalendarsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new WorkingCalendarsTable with assigned schema name
func (a WorkingCalendarsTable) FromSchema(schemaName string) *WorkingCalendarsTable {
	return newWorkingCalendarsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new WorkingCalendarsTable with assigned table prefix
func (a WorkingCalendarsTable) WithPrefix(prefix string) *WorkingCalendarsTable {
	return newWorkingCalendarsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new WorkingCalendarsTable with assigned table suffix
func (a WorkingCalendarsTable) WithSuffix(suffix string) *WorkingCalendarsTable {
	return newWorkingCalendarsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newWorkingCalendarsTable(schemaName, tableName, alias string) *WorkingCalendarsTable {
	return &WorkingCalendarsTable{
		workingCalendarsTable: newWorkingCalendarsTableImpl(schemaName, tableName, alias),
		EXCLUDED:              newWorkingCalendarsTableImpl("", "excluded", ""),
	}
}

func newWorkingCalendarsTableImpl(schemaName, tableName, alias string) workingCalendarsTable {
	var (
		IDColumn              = postgres.StringColumn("id")
		CompanyIDColumn       = postgres.StringColumn("company_id")
		BranchIDColumn        = postgres.StringColumn("branch_id")
		YearColumn            = postgres.IntegerColumn("year")
		DefaultWorkDaysColumn = postgres.IntegerArrayColumn("default_work_days")
		CreatedAtColumn       = postgres.TimestampzColumn("created_at")
		allColumns            = postgres.ColumnList{IDColumn, CompanyIDColumn, BranchIDColumn, YearColumn, DefaultWorkDaysColumn, CreatedAtColumn}
		mutableColumns        = postgres.ColumnList{CompanyIDColumn, BranchIDColumn, YearColumn, DefaultWorkDaysColumn, CreatedAtColumn}
		defaultColumns        = postgres.ColumnList{IDColumn, DefaultWorkDaysColumn, CreatedAtColumn}
	)

	return workingCalendarsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:              IDColumn,
		CompanyID:       CompanyIDColumn,
		BranchID:        BranchIDColumn,
		Year:            YearColumn,
		DefaultWorkDays: DefaultWorkDaysColumn,
		CreatedAt:       CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
