//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var ApplicationStatus = &struct {
	Applied     postgres.StringExpression
	Reviewed    postgres.StringExpression
	Interviewed postgres.StringExpression
	Offered     postgres.StringExpression
	Rejected    postgres.StringExpression
}{
	Applied:     postgres.NewEnumValue("applied"),
	Reviewed:    postgres.NewEnumValue("reviewed"),
	Interviewed: postgres.NewEnumValue("interviewed"),
	Offered:     postgres.NewEnumValue("offered"),
	Rejected:    postgres.NewEnumValue("rejected"),
}
