//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var AttendanceStatus = &struct {
	Present postgres.StringExpression
	Absent  postgres.StringExpression
	Late    postgres.StringExpression
	HalfDay postgres.StringExpression
	Holiday postgres.StringExpression
	Leave   postgres.StringExpression
	OffDay  postgres.StringExpression
}{
	Present: postgres.NewEnumValue("present"),
	Absent:  postgres.NewEnumValue("absent"),
	Late:    postgres.NewEnumValue("late"),
	HalfDay: postgres.NewEnumValue("half_day"),
	Holiday: postgres.NewEnumValue("holiday"),
	Leave:   postgres.NewEnumValue("leave"),
	OffDay:  postgres.NewEnumValue("off_day"),
}
