//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var EmploymentStatus = &struct {
	Active     postgres.StringExpression
	Resigned   postgres.StringExpression
	Terminated postgres.StringExpression
	OnLeave    postgres.StringExpression
}{
	Active:     postgres.NewEnumValue("active"),
	Resigned:   postgres.NewEnumValue("resigned"),
	Terminated: postgres.NewEnumValue("terminated"),
	OnLeave:    postgres.NewEnumValue("on_leave"),
}
