//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var EmploymentType = &struct {
	Permanent postgres.StringExpression
	Contract  postgres.StringExpression
	Probation postgres.StringExpression
	Intern    postgres.StringExpression
}{
	Permanent: postgres.NewEnumValue("permanent"),
	Contract:  postgres.NewEnumValue("contract"),
	Probation: postgres.NewEnumValue("probation"),
	Intern:    postgres.NewEnumValue("intern"),
}
