//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var ExperienceLevel = &struct {
	Entry  postgres.StringExpression
	Mid    postgres.StringExpression
	Senior postgres.StringExpression
	Lead   postgres.StringExpression
}{
	Entry:  postgres.NewEnumValue("entry"),
	Mid:    postgres.NewEnumValue("mid"),
	Senior: postgres.NewEnumValue("senior"),
	Lead:   postgres.NewEnumValue("lead"),
}
