//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var ExperienceType = &struct {
	Employment    postgres.StringExpression
	Gig           postgres.StringExpression
	Education     postgres.StringExpression
	Certification postgres.StringExpression
	Project       postgres.StringExpression
	Volunteering  postgres.StringExpression
}{
	Employment:    postgres.NewEnumValue("employment"),
	Gig:           postgres.NewEnumValue("gig"),
	Education:     postgres.NewEnumValue("education"),
	Certification: postgres.NewEnumValue("certification"),
	Project:       postgres.NewEnumValue("project"),
	Volunteering:  postgres.NewEnumValue("volunteering"),
}
