//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var JobLevel = &struct {
	Staff      postgres.StringExpression
	Supervisor postgres.StringExpression
	Manager    postgres.StringExpression
	Director   postgres.StringExpression
}{
	Staff:      postgres.NewEnumValue("staff"),
	Supervisor: postgres.NewEnumValue("supervisor"),
	Manager:    postgres.NewEnumValue("manager"),
	Director:   postgres.NewEnumValue("director"),
}
