//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var PayrollRunStatus = &struct {
	Draft      postgres.StringExpression
	Calculated postgres.StringExpression
	Approved   postgres.StringExpression
	Paid       postgres.StringExpression
}{
	Draft:      postgres.NewEnumValue("draft"),
	Calculated: postgres.NewEnumValue("calculated"),
	Approved:   postgres.NewEnumValue("approved"),
	Paid:       postgres.NewEnumValue("paid"),
}
