//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var VerificationStatus = &struct {
	Pending  postgres.StringExpression
	Verified postgres.StringExpression
	Rejected postgres.StringExpression
}{
	Pending:  postgres.NewEnumValue("pending"),
	Verified: postgres.NewEnumValue("verified"),
	Rejected: postgres.NewEnumValue("rejected"),
}
