//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type ActivityLogs struct {
	ID         uuid.UUID `sql:"primary_key"`
	CompanyID  uuid.UUID
	ActorID    uuid.UUID
	Action     string
	EntityType string
	EntityID   *uuid.UUID
	Metadata   *string
	CreatedAt  time.Time
}
