//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type AiEvaluations struct {
	ID           uuid.UUID `sql:"primary_key"`
	ProfileID    uuid.UUID
	OverallScore int32
	Strengths    string
	Weaknesses   string
	Suggestions  string
	SkillScores  string
	RawAnalysis  string
	CreatedAt    time.Time
}
