//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type ApplicationStatus string

const (
	ApplicationStatus_Applied     ApplicationStatus = "applied"
	ApplicationStatus_Reviewed    ApplicationStatus = "reviewed"
	ApplicationStatus_Interviewed ApplicationStatus = "interviewed"
	ApplicationStatus_Offered     ApplicationStatus = "offered"
	ApplicationStatus_Rejected    ApplicationStatus = "rejected"
)

var ApplicationStatusAllValues = []ApplicationStatus{
	ApplicationStatus_Applied,
	ApplicationStatus_Reviewed,
	ApplicationStatus_Interviewed,
	ApplicationStatus_Offered,
	ApplicationStatus_Rejected,
}

func (e *ApplicationStatus) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "applied":
		*e = ApplicationStatus_Applied
	case "reviewed":
		*e = ApplicationStatus_Reviewed
	case "interviewed":
		*e = ApplicationStatus_Interviewed
	case "offered":
		*e = ApplicationStatus_Offered
	case "rejected":
		*e = ApplicationStatus_Rejected
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for ApplicationStatus enum")
	}

	return nil
}

func (e ApplicationStatus) String() string {
	return string(e)
}
