//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Applications struct {
	ID           uuid.UUID `sql:"primary_key"`
	JobseekerID  uuid.UUID
	JobPostingID uuid.UUID
	Status       ApplicationStatus
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
