//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type ApplicationMessages struct {
	ID            uuid.UUID `sql:"primary_key"`
	ApplicationID uuid.UUID
	SenderUserID  uuid.UUID
	MessageType   string
	Body          string
	CreatedAt     time.Time
}
