//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type AttendanceStatus string

const (
	AttendanceStatus_Present AttendanceStatus = "present"
	AttendanceStatus_Absent  AttendanceStatus = "absent"
	AttendanceStatus_Late    AttendanceStatus = "late"
	AttendanceStatus_HalfDay AttendanceStatus = "half_day"
	AttendanceStatus_Holiday AttendanceStatus = "holiday"
	AttendanceStatus_Leave   AttendanceStatus = "leave"
	AttendanceStatus_OffDay  AttendanceStatus = "off_day"
)

var AttendanceStatusAllValues = []AttendanceStatus{
	AttendanceStatus_Present,
	AttendanceStatus_Absent,
	AttendanceStatus_Late,
	AttendanceStatus_HalfDay,
	AttendanceStatus_Holiday,
	AttendanceStatus_Leave,
	AttendanceStatus_OffDay,
}

func (e *AttendanceStatus) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "present":
		*e = AttendanceStatus_Present
	case "absent":
		*e = AttendanceStatus_Absent
	case "late":
		*e = AttendanceStatus_Late
	case "half_day":
		*e = AttendanceStatus_HalfDay
	case "holiday":
		*e = AttendanceStatus_Holiday
	case "leave":
		*e = AttendanceStatus_Leave
	case "off_day":
		*e = AttendanceStatus_OffDay
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for AttendanceStatus enum")
	}

	return nil
}

func (e AttendanceStatus) String() string {
	return string(e)
}
