//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
	"time"
)

type AttendanceLogs struct {
	ID              uuid.UUID `sql:"primary_key"`
	CompanyID       uuid.UUID
	EmployeeID      uuid.UUID
	Date            time.Time
	ClockIn         *time.Time
	ClockOut        *time.Time
	ClockInLat      *decimal.Decimal
	ClockInLng      *decimal.Decimal
	ClockOutLat     *decimal.Decimal
	ClockOutLng     *decimal.Decimal
	BranchID        *uuid.UUID
	IsInGeofence    *bool
	IsLate          bool
	LateMinutes     int32
	IsEarlyOut      bool
	OvertimeMinutes int32
	AttendanceCode  string
	CreatedAt       time.Time
}
