//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
	"time"
)

type Branches struct {
	ID                   uuid.UUID `sql:"primary_key"`
	CompanyID            uuid.UUID
	Name                 string
	BranchType           string
	ParentBranchID       *uuid.UUID
	Address              *string
	City                 *string
	Province             *string
	Latitude             *decimal.Decimal
	Longitude            *decimal.Decimal
	GeofenceRadiusMeters int32
	IsActive             bool
	CreatedAt            time.Time
}
