//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type EmploymentStatus string

const (
	EmploymentStatus_Active     EmploymentStatus = "active"
	EmploymentStatus_Resigned   EmploymentStatus = "resigned"
	EmploymentStatus_Terminated EmploymentStatus = "terminated"
	EmploymentStatus_OnLeave    EmploymentStatus = "on_leave"
)

var EmploymentStatusAllValues = []EmploymentStatus{
	EmploymentStatus_Active,
	EmploymentStatus_Resigned,
	EmploymentStatus_Terminated,
	EmploymentStatus_OnLeave,
}

func (e *EmploymentStatus) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "active":
		*e = EmploymentStatus_Active
	case "resigned":
		*e = EmploymentStatus_Resigned
	case "terminated":
		*e = EmploymentStatus_Terminated
	case "on_leave":
		*e = EmploymentStatus_OnLeave
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for EmploymentStatus enum")
	}

	return nil
}

func (e EmploymentStatus) String() string {
	return string(e)
}
