//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
)

type EmployeeIDConfigs struct {
	ID           uuid.UUID `sql:"primary_key"`
	CompanyID    uuid.UUID
	Prefix       string
	NextSequence int32
	Padding      int32
}
