//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
	"time"
)

type EmployeeSalary struct {
	ID            uuid.UUID `sql:"primary_key"`
	EmployeeID    uuid.UUID
	ComponentID   uuid.UUID
	Amount        decimal.Decimal
	EffectiveDate time.Time
	CreatedAt     time.Time
}
