//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
)

type EmployeeRoles struct {
	EmployeeID uuid.UUID `sql:"primary_key"`
	RoleID     uuid.UUID `sql:"primary_key"`
}
