//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
	"time"
)

type Employees struct {
	ID                       uuid.UUID `sql:"primary_key"`
	CompanyID                uuid.UUID
	UserID                   *uuid.UUID
	EmployeeIDNumber         string
	FirstName                string
	LastName                 string
	Email                    string
	Phone                    *string
	DateOfBirth              *time.Time
	Gender                   *string
	MaritalStatus            *string
	Address                  *string
	City                     *string
	Province                 *string
	PostalCode               *string
	NationalID               *string
	Npwp                     *string
	BpjsKesehatanID          *string
	BpjsKetenagakerjaanID    *string
	BankName                 *string
	BankAccountNumber        *string
	BankAccountHolder        *string
	EmergencyContactName     *string
	EmergencyContactPhone    *string
	EmergencyContactRelation *string
	EmploymentType           EmploymentType
	EmploymentStatus         EmploymentStatus
	JoinDate                 time.Time
	EndDate                  *time.Time
	DepartmentID             *uuid.UUID
	PositionID               *uuid.UUID
	BranchID                 *uuid.UUID
	ManagerID                *uuid.UUID
	BaseSalary               *decimal.Decimal
	CreatedAt                time.Time
	UpdatedAt                time.Time
}
