//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type EmploymentType string

const (
	EmploymentType_Permanent EmploymentType = "permanent"
	EmploymentType_Contract  EmploymentType = "contract"
	EmploymentType_Probation EmploymentType = "probation"
	EmploymentType_Intern    EmploymentType = "intern"
)

var EmploymentTypeAllValues = []EmploymentType{
	EmploymentType_Permanent,
	EmploymentType_Contract,
	EmploymentType_Probation,
	EmploymentType_Intern,
}

func (e *EmploymentType) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "permanent":
		*e = EmploymentType_Permanent
	case "contract":
		*e = EmploymentType_Contract
	case "probation":
		*e = EmploymentType_Probation
	case "intern":
		*e = EmploymentType_Intern
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for EmploymentType enum")
	}

	return nil
}

func (e EmploymentType) String() string {
	return string(e)
}
