//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type ExceptionStatus string

const (
	ExceptionStatus_Pending  ExceptionStatus = "pending"
	ExceptionStatus_Approved ExceptionStatus = "approved"
	ExceptionStatus_Rejected ExceptionStatus = "rejected"
)

var ExceptionStatusAllValues = []ExceptionStatus{
	ExceptionStatus_Pending,
	ExceptionStatus_Approved,
	ExceptionStatus_Rejected,
}

func (e *ExceptionStatus) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "pending":
		*e = ExceptionStatus_Pending
	case "approved":
		*e = ExceptionStatus_Approved
	case "rejected":
		*e = ExceptionStatus_Rejected
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for ExceptionStatus enum")
	}

	return nil
}

func (e ExceptionStatus) String() string {
	return string(e)
}
