//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type ExperienceLevel string

const (
	ExperienceLevel_Entry  ExperienceLevel = "entry"
	ExperienceLevel_Mid    ExperienceLevel = "mid"
	ExperienceLevel_Senior ExperienceLevel = "senior"
	ExperienceLevel_Lead   ExperienceLevel = "lead"
)

var ExperienceLevelAllValues = []ExperienceLevel{
	ExperienceLevel_Entry,
	ExperienceLevel_Mid,
	ExperienceLevel_Senior,
	ExperienceLevel_Lead,
}

func (e *ExperienceLevel) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "entry":
		*e = ExperienceLevel_Entry
	case "mid":
		*e = ExperienceLevel_Mid
	case "senior":
		*e = ExperienceLevel_Senior
	case "lead":
		*e = ExperienceLevel_Lead
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for ExperienceLevel enum")
	}

	return nil
}

func (e ExperienceLevel) String() string {
	return string(e)
}
