//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type ExperienceType string

const (
	ExperienceType_Employment    ExperienceType = "employment"
	ExperienceType_Gig           ExperienceType = "gig"
	ExperienceType_Education     ExperienceType = "education"
	ExperienceType_Certification ExperienceType = "certification"
	ExperienceType_Project       ExperienceType = "project"
	ExperienceType_Volunteering  ExperienceType = "volunteering"
)

var ExperienceTypeAllValues = []ExperienceType{
	ExperienceType_Employment,
	ExperienceType_Gig,
	ExperienceType_Education,
	ExperienceType_Certification,
	ExperienceType_Project,
	ExperienceType_Volunteering,
}

func (e *ExperienceType) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "employment":
		*e = ExperienceType_Employment
	case "gig":
		*e = ExperienceType_Gig
	case "education":
		*e = ExperienceType_Education
	case "certification":
		*e = ExperienceType_Certification
	case "project":
		*e = ExperienceType_Project
	case "volunteering":
		*e = ExperienceType_Volunteering
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for ExperienceType enum")
	}

	return nil
}

func (e ExperienceType) String() string {
	return string(e)
}
