//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
	"time"
)

type HrAnalyticsSnapshots struct {
	ID                  uuid.UUID `sql:"primary_key"`
	CompanyID           uuid.UUID
	SnapshotMonth       time.Time
	TotalHeadcount      int32
	NewHires            int32
	Terminations        int32
	TurnoverRate        decimal.Decimal
	AvgTenureMonths     decimal.Decimal
	DepartmentBreakdown string
	CreatedAt           time.Time
}
