//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type InteractionType string

const (
	InteractionType_Applied     InteractionType = "applied"
	InteractionType_Interviewed InteractionType = "interviewed"
)

var InteractionTypeAllValues = []InteractionType{
	InteractionType_Applied,
	InteractionType_Interviewed,
}

func (e *InteractionType) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "applied":
		*e = InteractionType_Applied
	case "interviewed":
		*e = InteractionType_Interviewed
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for InteractionType enum")
	}

	return nil
}

func (e InteractionType) String() string {
	return string(e)
}
