//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"github.com/lib/pq"
	"time"
)

type JobPostings struct {
	ID                  uuid.UUID `sql:"primary_key"`
	CompanyID           uuid.UUID
	Title               string
	Description         string
	Industry            string
	Tags                *pq.StringArray
	RequiredSkills      *pq.StringArray
	ExperienceLevel     *ExperienceLevel
	Location            *string
	SalaryRange         *string
	Status              JobStatus
	CreatedAt           time.Time
	Requirements        *string
	YearsExperienceMin  *int32
	YearsExperienceMax  *int32
	IsFreshGradFriendly bool
}
