//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type JobLevel string

const (
	JobLevel_Staff      JobLevel = "staff"
	JobLevel_Supervisor JobLevel = "supervisor"
	JobLevel_Manager    JobLevel = "manager"
	JobLevel_Director   JobLevel = "director"
)

var JobLevelAllValues = []JobLevel{
	JobLevel_Staff,
	JobLevel_Supervisor,
	JobLevel_Manager,
	JobLevel_Director,
}

func (e *JobLevel) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "staff":
		*e = JobLevel_Staff
	case "supervisor":
		*e = JobLevel_Supervisor
	case "manager":
		*e = JobLevel_Manager
	case "director":
		*e = JobLevel_Director
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for JobLevel enum")
	}

	return nil
}

func (e JobLevel) String() string {
	return string(e)
}
