//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"github.com/lib/pq"
)

type JobExperiences struct {
	ID           uuid.UUID `sql:"primary_key"`
	ProfileID    uuid.UUID
	Type         ExperienceType
	Title        string
	Organization string
	StartDate    string
	EndDate      *string
	IsCurrent    bool
	Description  *string
	Industry     *string
	SkillsUsed   *pq.StringArray
	URL          *string
}
