//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type LeaveTypes struct {
	ID                 uuid.UUID `sql:"primary_key"`
	CompanyID          uuid.UUID
	Name               string
	Code               string
	DefaultDaysPerYear int32
	IsPaid             bool
	RequiresAttachment bool
	IsActive           bool
	CreatedAt          time.Time
}
