//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type LeaveRequests struct {
	ID              uuid.UUID `sql:"primary_key"`
	CompanyID       uuid.UUID
	EmployeeID      uuid.UUID
	LeaveTypeID     uuid.UUID
	StartDate       time.Time
	EndDate         time.Time
	TotalDays       int32
	Reason          string
	AttachmentURL   *string
	Status          LeaveRequestStatus
	ReviewerID      *uuid.UUID
	ReviewerComment *string
	ReviewedAt      *time.Time
	CreatedAt       time.Time
}
