//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type LeaveBalances struct {
	ID            uuid.UUID `sql:"primary_key"`
	EmployeeID    uuid.UUID
	LeaveTypeID   uuid.UUID
	Year          int32
	TotalDays     int32
	UsedDays      int32
	CarryOverDays int32
	CreatedAt     time.Time
}
