//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type LeaveRequestStatus string

const (
	LeaveRequestStatus_Pending   LeaveRequestStatus = "pending"
	LeaveRequestStatus_Approved  LeaveRequestStatus = "approved"
	LeaveRequestStatus_Rejected  LeaveRequestStatus = "rejected"
	LeaveRequestStatus_Cancelled LeaveRequestStatus = "cancelled"
)

var LeaveRequestStatusAllValues = []LeaveRequestStatus{
	LeaveRequestStatus_Pending,
	LeaveRequestStatus_Approved,
	LeaveRequestStatus_Rejected,
	LeaveRequestStatus_Cancelled,
}

func (e *LeaveRequestStatus) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "pending":
		*e = LeaveRequestStatus_Pending
	case "approved":
		*e = LeaveRequestStatus_Approved
	case "rejected":
		*e = LeaveRequestStatus_Rejected
	case "cancelled":
		*e = LeaveRequestStatus_Cancelled
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for LeaveRequestStatus enum")
	}

	return nil
}

func (e LeaveRequestStatus) String() string {
	return string(e)
}
