//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type OnboardingTemplateTasks struct {
	ID           uuid.UUID `sql:"primary_key"`
	TemplateID   uuid.UUID
	Title        string
	Description  string
	SortOrder    int32
	DueDays      int32
	AssigneeRole string
	CreatedAt    time.Time
}
