//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
	"time"
)

type PayrollRuns struct {
	ID              uuid.UUID `sql:"primary_key"`
	CompanyID       uuid.UUID
	PeriodStart     time.Time
	PeriodEnd       time.Time
	Status          PayrollRunStatus
	TotalGross      decimal.Decimal
	TotalDeductions decimal.Decimal
	TotalNet        decimal.Decimal
	EmployeeCount   int32
	Notes           *string
	RunBy           *uuid.UUID
	ApprovedBy      *uuid.UUID
	ApprovedAt      *time.Time
	CreatedAt       time.Time
}
