//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type PayrollRunStatus string

const (
	PayrollRunStatus_Draft      PayrollRunStatus = "draft"
	PayrollRunStatus_Calculated PayrollRunStatus = "calculated"
	PayrollRunStatus_Approved   PayrollRunStatus = "approved"
	PayrollRunStatus_Paid       PayrollRunStatus = "paid"
)

var PayrollRunStatusAllValues = []PayrollRunStatus{
	PayrollRunStatus_Draft,
	PayrollRunStatus_Calculated,
	PayrollRunStatus_Approved,
	PayrollRunStatus_Paid,
}

func (e *PayrollRunStatus) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "draft":
		*e = PayrollRunStatus_Draft
	case "calculated":
		*e = PayrollRunStatus_Calculated
	case "approved":
		*e = PayrollRunStatus_Approved
	case "paid":
		*e = PayrollRunStatus_Paid
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for PayrollRunStatus enum")
	}

	return nil
}

func (e PayrollRunStatus) String() string {
	return string(e)
}
