//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
	"time"
)

type Payslips struct {
	ID              uuid.UUID `sql:"primary_key"`
	PayrollRunID    uuid.UUID
	EmployeeID      uuid.UUID
	GrossPay        decimal.Decimal
	TotalDeductions decimal.Decimal
	NetPay          decimal.Decimal
	Breakdown       string
	CreatedAt       time.Time
}
