//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Positions struct {
	ID           uuid.UUID `sql:"primary_key"`
	CompanyID    uuid.UUID
	Name         string
	DepartmentID *uuid.UUID
	Level        JobLevel
	CreatedAt    time.Time
}
