//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
	"time"
)

type SalaryComponents struct {
	ID            uuid.UUID `sql:"primary_key"`
	CompanyID     uuid.UUID
	Name          string
	Code          string
	Type          SalaryComponentType
	IsTaxable     bool
	IsFixed       bool
	DefaultAmount decimal.Decimal
	IsActive      bool
	CreatedAt     time.Time
}
