//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type SalaryComponentType string

const (
	SalaryComponentType_Earning   SalaryComponentType = "earning"
	SalaryComponentType_Deduction SalaryComponentType = "deduction"
)

var SalaryComponentTypeAllValues = []SalaryComponentType{
	SalaryComponentType_Earning,
	SalaryComponentType_Deduction,
}

func (e *SalaryComponentType) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "earning":
		*e = SalaryComponentType_Earning
	case "deduction":
		*e = SalaryComponentType_Deduction
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for SalaryComponentType enum")
	}

	return nil
}

func (e SalaryComponentType) String() string {
	return string(e)
}
