//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"github.com/lib/pq"
	"github.com/shopspring/decimal"
	"time"
)

type ShiftTemplates struct {
	ID                   uuid.UUID `sql:"primary_key"`
	CompanyID            uuid.UUID
	Name                 string
	StartTime            time.Time
	EndTime              time.Time
	BreakDurationMinutes int32
	LateToleranceMinutes int32
	OvertimeMultiplier   decimal.Decimal
	ApplicableDays       pq.Int32Array
	IsDefault            bool
	CreatedAt            time.Time
}
