//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type VerificationStatus string

const (
	VerificationStatus_Pending  VerificationStatus = "pending"
	VerificationStatus_Verified VerificationStatus = "verified"
	VerificationStatus_Rejected VerificationStatus = "rejected"
)

var VerificationStatusAllValues = []VerificationStatus{
	VerificationStatus_Pending,
	VerificationStatus_Verified,
	VerificationStatus_Rejected,
}

func (e *VerificationStatus) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "pending":
		*e = VerificationStatus_Pending
	case "verified":
		*e = VerificationStatus_Verified
	case "rejected":
		*e = VerificationStatus_Rejected
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for VerificationStatus enum")
	}

	return nil
}

func (e VerificationStatus) String() string {
	return string(e)
}
