//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"github.com/lib/pq"
	"time"
)

type WorkingCalendars struct {
	ID              uuid.UUID `sql:"primary_key"`
	CompanyID       uuid.UUID
	BranchID        *uuid.UUID
	Year            int32
	DefaultWorkDays pq.Int32Array
	CreatedAt       time.Time
}
